### ISSUE TITLE
Additional configuration options

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#10]
Client: 
- [ ] Toggle visibility of different model types

**Comment by Steveplays28** [comment]
Custom config system go brr, might want to rename this issue, because the config options are interesting

**Comment by SigmundGranaas** [comment]
Your config system basically annihilated these issue, I'll keep it for adding some neat options that should be added to the config.

**Comment by JorisDeBeer** [comment]
Custom config has been implemented, we can just make a new Issue when we think of stuff to add right?
