### ISSUE TITLE
Enderite Compatibility

### ISSUE THREAD

**Issue by TheShadyyOneYT** [SigmundGranaas/forgero#1027]
Enderite mod: https://modrinth.com/mod/enderite-mod

**Comment by Apocip0** [comment]
Looks easy enough. Although the Charge effect seems advanced, I'll have to let the developers know if that's possible to implement something like that. We'll see about that.

The compatibility will be added. Thank you.

**Comment by TheShadyyOneYT** [comment]
np :)

**Comment by JorisDeBeer** [comment]
Items will be merged in coming pr
