### ISSUE TITLE
Tooltip only shows up for a single variant of items that has a common resource

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#1031]
![image](https://github.com/user-attachments/assets/8228c03e-4b83-4bb4-ab5c-107c53c6143c)
![image](https://github.com/user-attachments/assets/5da22c82-09cb-4099-93c8-7c6b38d8316b)

In this case, create and meadows both use the common limestone material. Tooltips needs to resolve to every possible material variant, not just the selected default.

**Comment by JorisDeBeer** [comment]
this should not be the case? Did you triple check?

**Comment by SigmundGranaas** [comment]
Yeah I have checked several materials. I also think I know why it does this. It's code related.

**Comment by JorisDeBeer** [comment]
Oh I did some testing with other biomes mods with their woods and those tags seemed to work fine with the tooltip, thats why I am confused. 

Seems there are still some holes in the common system currently

**Comment by SigmundGranaas** [comment]
Yeah it's not a huge issue, I just need to add some more code to check wether an item is possibly inside a common tag, and not just a direct reference. A lot of places I just pretend like the tag is actually just the one of the items inside of the tag to make things easier
