### ISSUE TITLE
Random tag error about cherry and iron invalidates recipes

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#1062]
![image](https://github.com/user-attachments/assets/24c5a398-d2d8-4a72-9136-17a5e4c36c8e)

Only happens with this mod installed.

**Comment by JorisDeBeer** [comment]
Joke this is apparently random? also happens without mods installed

**Comment by SigmundGranaas** [comment]
Seems to be a race condition due to handling this in a parallel stream.

**Comment by JorisDeBeer** [comment]
So I am not crazy luckily
