### ISSUE TITLE
Types are ignored after recent handler/multithreading updates 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#1080]
SOFT_MATERIAL is suddenly allowed in offensive slots causing tooltip and tool to bug out

**Comment by SigmundGranaas** [comment]
Hasn't this always been the case? The offensive material slots can accept any type of material. Or were you thinking of another slot?

**Comment by JorisDeBeer** [comment]
what

**Comment by JorisDeBeer** [comment]
![image](https://github.com/user-attachments/assets/1756e64f-4d04-40c5-bbba-432aa2977fbe)

Offensive material is very very ancient.

With all the new materials I made new types, with "upgrade materials" being almost everything 

Except for the following 
![image](https://github.com/user-attachments/assets/1464d04b-92e7-47d9-94b2-03aa713e1540)
 
As this fits under slot -> material 
and upgrade is also a child of material

**Comment by JorisDeBeer** [comment]
wait how long has this been "broken". 

Ur not gonna tell me that "type" in the schematic slot does not even work right?

**Comment by SigmundGranaas** [comment]
```
{
        "category": [
          "UTILITY"
        ],
        "type": "SWORD_GUARD"
      }
```

The type decides which type of content can fit in the slot, and the category decides which attributes will be picked from item on the slot

**Comment by JorisDeBeer** [comment]
Yea so why do "soft materials" go into the upgrade_material slot while they are no child type of that?

**Comment by SigmundGranaas** [comment]
I have no idea. I thought they were a subtype of upgrade material. I'll go digging

**Comment by SigmundGranaas** [comment]
https://github.com/user-attachments/assets/c28d0e42-035b-474d-98e2-0738577fcf31

I can't put it in

**Comment by SigmundGranaas** [comment]
It looks like sword are still using the MATERIAL type though:

```
{
        "upgrade_type": "SMITHING",
        "category": [
          "OFFENSIVE"
        ],
        "description": "reinforcement",
        "type": "MATERIAL"
      },
```

**Comment by JorisDeBeer** [comment]
oh
