### ISSUE TITLE
Config options to disable specific materials and schematics

### ISSUE THREAD

**Issue by Hexicube** [SigmundGranaas/forgero#1121]
I'd like to be able to disable some materials and schematics without disabling entire packs, notably I want to be able to remove all wood materials and all but one stone material which is part of the vanilla pack.

Currently creating/editing materials requires a full mod and can't be done through a datapack, additionally it doesn't look like extension mods would have the ability to do this and would instead require them to basically recreate the entire pack you want to remove a material or schematic from.

I mostly want to do this as an anti-clutter measure as I may end up creating a material tweak mod regardless.

Alternatively, if this can be done through a tweak mod, that wasn't clear on the example repo and there should be a file showing how to remove a material/schematic.

**Comment by JorisDeBeer** [comment]
There should be a option in the config to disable specific materials and schematics. I am unsure if it still works tho as it has been having some issues in the past. 

![image](https://github.com/user-attachments/assets/a26aecba-5bc0-44b0-9b89-e457c8027267)

disabledResources should be able to do what you want.

**Comment by Hexicube** [comment]
Working fine for materials, wasn't clear that I had to put the namespace in front.

Doing it for schematics doesn't work the same (or at all), but since most of them are going to be removed regardless I'll just wait for that.
