### ISSUE TITLE
Schematics can't be used to make parts

### ISSUE THREAD

**Issue by Hexicube** [SigmundGranaas/forgero#1122]
The following schematics have no recipes for turning materials into parts:

- Saber
- Agile Guard
- Kimiri Sword
- Tree Feller Axe
- Lightweight Pickaxe
- Slanted Sword
- Duelling Guard
- Spiked Binding
- Path Digger Shovel
- Ore Mining Pickaxe
- Grave Digger Shovel
- Scimitar
- Tree Chopper Axe
- Shortsword
- Serrated Sword
- Path Mining Pickaxe
- Reaper
- Refined Handle
- Spear
- Sickle
- Entrenching Shovel
- War Hammer
- Felling Axe
- Knife
- Mandrill (the reason I noticed, I found this schematic in survival and wanted to use it)
- Spade
- Hammer
- Half Basket Guard
- Cruciform Guard
- Rounded Guard
- Swept Guard
- Shell Guard
- Mechanized Guard
- Tsuba Guard
- Mastercrafted Handle

Happens on 0.13.0 and 0.13.1, from the looks of things every single blueprint that's broken is from an internal pack that isn't the base vanilla one.

**Comment by JorisDeBeer** [comment]
Should be fixed for most of the new stuff. Some stuff like the mastercrafted handles etc we discontinoued so will not be receiving this fix
