### ISSUE TITLE
New gems in chests sometimes have doubled effect strength for their level

### ISSUE THREAD

**Issue by Hexicube** [SigmundGranaas/forgero#1123]
It's unclear if this is a bug based on NBT values, however some looted gems have double the strength that they should have based on the 0.13 release.

https://i.imgur.com/IGs1Jc9.png

I have two Prismarine lv5 gems from looting a Deep Dark city, the "level 1" gem is correctly +5 but the "level 2" gem is +10 instead.

I also have two Amethyst gems that are both lv4, except this time level 2 and 3 giving +8 and +12.

Based on the lack of recipes this seems to be a holdover from the old gem system of merging gems to improve them, except they're still incorrectly generating as loot when it looks like the system was going to be discarded.

**Comment by JorisDeBeer** [comment]
We suspect this is indeed a left over from ancient times. We are betting on this being fixed when we actually remove the old stuff otherwise we will look into the droptable. Keeping it open for now.
