### ISSUE TITLE
[suggestion] compatability with mythic metals?

### ISSUE THREAD

**Issue by netcore10** [SigmundGranaas/forgero#114]
https://www.curseforge.com/minecraft/mc-mods/mythicmetals

**Comment by netcore10** [comment]
I couldn't find anything in docs about adding compatability with modded materials so i assumed it wasn't possible.

**Comment by SigmundGranaas** [comment]
Hi! There is currently no documentation for how to add support for other materials from other mods. But the system will register material from all installed mods if files are placed in the right folder. See [materials](https://github.com/SigmundGranaas/forgero/tree/v0.7.3-beta/src/main/resources/data/forgero/materials/simple)
One of the goals for the Beta is to stabilize the API for materials, schematics and gems, and add mod dependencies to all dynamically loaded resources. I will create a guide on the wiki once I have decided on the final format for the resources, which should not be far away. Some work will have to be done creating unique attributes for new materials depending on which tool part it is being used for. I might also create an example mod, showcasing all the different ways you could add custom resources to the mod, as well as add compatibility with other mods.

**Comment by netcore10** [comment]
Oh i see! Thanks for the clarrification. I think i'll wait for it to be a little more defined.

**Comment by SigmundGranaas** [comment]
Experimental support for Mythic Metals (MM) has been added in the upcoming 0.8.0 release which includes a declared schema for resources. The release will start off as a release candidate, and will be published to CurseForge under the Beta tag until the final version of 0.8.0 is complete.

This version includes support for most of the metals from MM, but mostly for testing compatability and how well the system performs. All of the files declaring the attributes for the metals are found in: [Mythic Metals material directory](https://github.com/SigmundGranaas/forgero/tree/resource_schema_v1/src/main/resources/data/forgero/materials/mythicmetals). None of the materials have unique attributes right now. It takes a lot of time to test and declare all of the properties and behaviour of every single material, and MM has a lot of them. Creating interesting and balanced attributes for every metal will take some effort, and it won't be possible for me to do this anytime soon. Documentation for the material properties isn't available yet, but will be created as a part of the 0.8.0 release. Still, all of the properties are mostly finalized, which means that you could look at what the vanilla materials do, and use that as a baseline.

This test also shows that every single schematic cannot have an item linked to it, as generating recipes for all items gets really slow when adding a lot of new materials.

**Comment by SigmundGranaas** [comment]
TODO:
- [x] Refine palettes used for creating texture for MM
- [ ] Balance the material properties
- [x] Add translations for all materials
- [x] Optimise recipe registry
- [ ] Add missing materials
- [ ] Look into adding support for gems using the new materials
