### ISSUE TITLE
No Schematic Output On Vanilla Tools 

### ISSUE THREAD

**Issue by greensad** [SigmundGranaas/forgero#117]
![2022-05-20_09 59 53](https://user-images.githubusercontent.com/10079877/169544812-9a82475d-8d51-438d-a0d0-daab1ae33f59.png)

Guessing this is a compatibility issue with another mod but as of now I'm unsure how to acquire any schematic unless I cheat in a toolpart. Tools from other mods do yield schematics when used however.

**Comment by SigmundGranaas** [comment]
Recipes for schematics relied on Fabrics tool tags, but they were removed when deleting the Tool attribute API when updating to 1.18.2. That meant that all vanilla tools were removed from this tag, but all modded tools worked like they should. 

Issue is fixed, and some other missing schematic recipes has ben added in #116 . I will publish the update as soon as I have looked into some other bugs. Thanks for letting me know about the issue!
