### ISSUE TITLE
Packet issue.

### ISSUE THREAD

**Issue by netcore10** [SigmundGranaas/forgero#118]
With forgero installed, server side clients get kicked for oversized packets even with extra large packets or connectivity installed. 

Client log at time of issue
[latest_client (3).log](https://github.com/SigmundGranaas/forgero/files/8744892/latest_client.3.log)

server log at time of issue
[logs_latest_server (5).log](https://github.com/SigmundGranaas/forgero/files/8744893/logs_latest_server.5.log)

hope this helps for the future (had to remove your mod for now)

**Comment by SigmundGranaas** [comment]
Interesting! I will have a look at it these logs. I have not encountered issues like this when testing on an dedicated server, but I have only tested with minimal mods enabled. Are you using a modpack which I can use to replicate your environment?

**Comment by netcore10** [comment]
I am! 0.15 on https://www.curseforge.com/minecraft/modpacks/haywen-unity-fe/files/3789071 is where the issue of packets happened

**Comment by SigmundGranaas** [comment]
Nice! I'll get back to you after I've done some testing

**Comment by SigmundGranaas** [comment]
I was able to replicate the issue using the mod pack and a dedicated server. I struggled to understand how Forgero could cause this issue. I did some googling around and saw that some people were struggling with this error when trying to load a mod configuration that was too heavy. Removing Forgero solved the issue for me on the dedicated server, but removing other mods from the mod mod pack also solved the issue. The mod I tried removing was Botania.

Could this be an issue related to the amount of mods being loaded? It would be nice if you could try removing other mods in your configuration to verify if this solves the issue for you too.

Also, thanks for taking the time to test my mod, I appreciate it!

**Comment by netcore10** [comment]
The xlpackets mod is supposed to help, there's even packs much bigger than my own. Somebody else also said that jello does it, or it could be related to a library, but removing your mod seemed to be the only solution.

**Comment by netcore10** [comment]
To clarify, i did try to lower the mod count, but it didn't work on my end.

**Comment by SigmundGranaas** [comment]
I'll test some different configuration of mods to see which combinations cause issues.

**Comment by SigmundGranaas** [comment]
Seems like the mods increasing packets size are not updated to 1.18, but it does not look like there is a lot of code involved.

**Comment by SigmundGranaas** [comment]
SOLVED.

Packet sizes greater than 8388608 is hardcoded to create an error when connecting. I created a small mod doubling this limit, and this seems to make everything run as it is supposed to. Some mods increase the packet size a lot, and some don't, Forgero is one of those, as well as Botania. Removing any of these mods solves the issue.

I'll release the mini-mod as a separate mod on CurseForge, as I really don't know if this packet limiter has any important function inside Minecraft, and I don't want to include it in Forgero.

**Comment by SigmundGranaas** [comment]
Mod is released at [Packet Size Doubler](https://curseforge.com/minecraft/mc-mods/packet-size-double)
Would be great if you could test this at your end as well!

Edit: Mod is hidden until approved by CurseForge

**Comment by netcore10** [comment]
oh my god you're a life saver. It'll take some time to test once it's approved

**Comment by SigmundGranaas** [comment]
[download link](https://easyupload.io/fu3sbn) Here's the file, if CurseForge takes a while to approve the mod.

**Comment by netcore10** [comment]
I'll get to testing once my server provider's back up.

**Comment by netcore10** [comment]
we're good!

**Comment by SigmundGranaas** [comment]
Great!

**Comment by netcore10** [comment]
thanks so much, i really appreciate it.

**Comment by SigmundGranaas** [comment]
No problem, just be sure to leave some feedback if you encounter more issues, or if you have any feedback on the mod!

**Comment by netcore10** [comment]
This isn't causing server crashes, but the server get's spammed sometimes on save with
[packeterror.txt](https://github.com/SigmundGranaas/forgero/files/8748538/packeterror.txt)
i assume it's your packet mod, sinse it's not on curse yet, i can only surmise.

**Comment by netcore10** [comment]
took a while for it to show on the console, almost didn't notice.

**Comment by netcore10** [comment]
here's the whole log of the running server
[logs_latest (1).log](https://github.com/SigmundGranaas/forgero/files/8748543/logs_latest.1.log)

**Comment by SigmundGranaas** [comment]
I am trying to recreate the issue, but I can't be able force the errors to occur. I have been running a server for over an hour, constantly triggering saves, but nothing really happens. Are you testing on a fresh world? I might have to test running the server on another computer to see if the issues occur when latency increases.

The errors don't come from any of the classes the mod makes changes to, but these errors might also be the reason the packet size limiter were created in the first place. Weird issue

**Comment by netcore10** [comment]
it could be just a freak accident or someone tried to join with mismatching mods, i'll concider it a me problem, sorry for all the hasstle.

**Comment by SigmundGranaas** [comment]
No worries

**Comment by netcore10** [comment]
I'm still getting a lot out of bounds packet issues, mainly with player interactions, player's logging off, etc. Are you sure it's not packet doubler?
[logs_latest (4).log](https://github.com/SigmundGranaas/forgero/files/8763599/logs_latest.4.log)


Current pack version: https://www.curseforge.com/minecraft/modpacks/haywen-unity-fe/files/3802794

**Comment by SigmundGranaas** [comment]
It is entirely possible that Packet doubler is causing this issue, it is very likely. I would like to be able to look into the issue, but I couldn't reproduce the issue on my end. I can give it another go with the updated modpack, but with the huge amount of mods there a lot of things that might cause issues with the expanded packet size. Unless I can reproduce the issue consistently, it is almost impossible for me to debug it.

**Comment by SigmundGranaas** [comment]
Also, I'm shit at network programming

**Comment by netcore10** [comment]
ah i'm verry sorry, atleast it's not game breaking, you've at least made it possible to play.

**Comment by SigmundGranaas** [comment]
If you are experiencing the issue, a lot of other people will also experience it. It would be really nice to resolve it, but it might also be hardware/config related, which might be why I can't recreate it, as I am running quite similar hardware on my desktop/servers. If we find a way to trigger this warning/error consistently I can fix it. I'll have another go with the newest modpack release, then I'll see if I can encounter it.

What is the hardware configuration you are running the server on?

**Comment by netcore10** [comment]
Hard to say because it's hosted by a service (Bisect hosting).

**Comment by SigmundGranaas** [comment]
Yeah, it would be quite hard to test if its related to hardware on those services.

**Comment by netcore10** [comment]
thanks for getting us playable though, you really saved us. you'll have a special spot in our mudpack's 'special thanks' credits c: i really appreciate it. I'll keep it as "Hardware issue"

**Comment by TheButterbrotMan** [comment]
@netcore10 Any news on this, could you solve this problem?

**Comment by TheButterbrotMan** [comment]
Also i can recreate this issue, no matter of system specs.

**Comment by netcore10** [comment]
@TheButterbrotMan Oh whoops! Yeah it was forgero and botania forcing a packet size limit. There's a 2 times packet fix now on curse
