### ISSUE TITLE
You get all this advancment at creating a new world without doing anything

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#142]
![image](https://user-images.githubusercontent.com/64548098/171508937-f3900470-de25-4611-9251-0ec8b824e8bd.png)

**Comment by SigmundGranaas** [comment]
It's supposed to only be triggered when picking up certain items from Forgero, but it seems like it is being triggered by every item. I am working on a fix!

**Comment by SigmundGranaas** [comment]
Fixed and released as 1.18.2-beta-0.8.3
