### ISSUE TITLE
Multi-head tool support (paxels/AIOTs)

### ISSUE THREAD

**Issue by tacticalretard** [SigmundGranaas/forgero#150]
Seeing as Tinker's Construct had Mattocks, a combo axe/shovel, I wanted to ask if multi-headed tools would ever be considered? The best example I can give is the Tetra mod, which allows you to take a tool and make it double-headed, penalizing certain aspects of each head like each head's material mining speed with the benefit of having two tools in one.

**Comment by SigmundGranaas** [comment]
I am definitely considering adding support for creating tools with combined functionality. I don't have an exact plan for how I would implement it, and there are lots of issues I need to resolve before I can start working on it, so don't expect it any time soon.

The approach I would take, is the ability to upgrade/combine schematics. This would allow you to copy certain properties from a compatible schematic to another one, like looks, functionality or some attributes. This would of course have to be balanced in some ways, but that's a problem for another day

**Comment by SigmundGranaas** [comment]
See my last comment on #448 for info about the state of multi-head support.
