### ISSUE TITLE
Unable to Launch [Fabric]

### ISSUE THREAD

**Issue by ardissaps** [SigmundGranaas/forgero#151]
Fabric Error : 
https://pastebin.com/XJwPXZQ7

MC Log : 
https://pastebin.com/bvpgqiZs

Launcher Log : 
https://paste.atlauncher.com/view/bb79aecb-bedc-427b-ada0-8b6be16a0a58

**Comment by SigmundGranaas** [comment]
Hi! It seems like the error originates in the prelaunch stage for ARRP, I could not make out if Forgero caused an error during prelaunch or if there was an error with the entrypoints.

Nevertheless, Forgero's use of the prelaunch entrypoint is redundant and not necessary. So I removed it. I updated to Forgero 0.8.5, and published it to curseforge. It would be nice if you could test this new version to see if it resolves this issue.

You were using 0.9.0-pre3 which is a WIP, it might take a while to merge the patch into this version, as I don't have that much time right now. I'll continue to update it till I think it's stable, but I will prioritize stability and compatability patches for 0.8.x as long as it is the main version.

Thanks for the report!

**Comment by ardissaps** [comment]
> You were using 0.9.0-pre3 which is a WIP

Yeah figured it out.

> Forgero 0.8.5

This one works perfectly, thank you. Now only need to wait for bows. :p
