### ISSUE TITLE
Feature: Add Bows

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#153]
I would like if you could cover Bows with this mod also.

**Comment by SigmundGranaas** [comment]
Bows are coming. There are loads of issues I would like to fix before I can add bows though, so development of this feature probably won't start anytime soon.

**Comment by SigmundGranaas** [comment]
Current plan is tools -> weapons -> bows -> Armor.

I am currently working on weapons

**Comment by TheButterbrotMan** [comment]
Nice!
