### ISSUE TITLE
Vanillarecipes are not deleted

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#155]
I can craft vanilla pickaxes and forgero pickaxes, but i think only forgero pickaxe should be able to craft.

**Comment by SigmundGranaas** [comment]
I don't know if disabling vanilla recipes should be the default behaviour, as it can break a lot of compat with other mods. I prefer if Forgero is the least intrusive as possible. Disabling vanilla recipes can be done with a simple kubeJS script.

I might add this functionality, but it will definitely be opt-in through configuration files.
