### ISSUE TITLE
Default tools in creative have their tool type in the name twice

### ISSUE THREAD

**Issue by Nathan22211** [SigmundGranaas/forgero#157]
e.g. oak sword sword

**Comment by SigmundGranaas** [comment]
Is this in 0.9.0-pre3?

**Comment by Nathan22211** [comment]
0.8.4 beta

**Comment by SigmundGranaas** [comment]
Thanks! I'll get that fixed for 0.8.5 and 0.9.0

**Comment by SigmundGranaas** [comment]
Could you share a screenshot of this issue? I don't seems to encounter it in later versions. 

Nvm, it's present in the 1.19 versions. I looked at 1.18.2. Will fix for 0.9.1-1.19
