### ISSUE TITLE
Adding the functionality to disable for example Vein Mining

### ISSUE THREAD

**Issue by TheButterbrotMan** [SigmundGranaas/forgero#158]
Hello, i would like to remove the Vein Mining Schematics from my modpack. How could i do that?

**Comment by SigmundGranaas** [comment]
All schematics are provided as individual files under data/forgero/schematic/SCHEMATIC_NAME.json 
Removing or editing the file before launching the game will edit/remove the schematic when playing. I am working on update 0.9.0 which overhauls the schematic, so the format might change a little soon.

**Comment by SigmundGranaas** [comment]
Might add an option to disable specific resources in a config file, but there's more work required before I could implement that functionality.
