### ISSUE TITLE
Polymorph Glitch

### ISSUE THREAD

**Issue by ardissaps** [SigmundGranaas/forgero#172]
![image](https://user-images.githubusercontent.com/82106625/175757142-81758000-24b7-444e-b542-ed2ffc907b4c.png)
https://www.curseforge.com/minecraft/mc-mods/polymorph-fabric

**Comment by SigmundGranaas** [comment]
There was an issue with duplicated recipes, after I changed the recipes to use tags instead of depending on individual items.

Will be fixed by #173 

Thanks for the heads up!

**Comment by ardissaps** [comment]
You are welcome! I'll report again if found bug and others.

**Comment by ardissaps** [comment]
![image](https://user-images.githubusercontent.com/82106625/175778005-7412e2ff-c01b-4427-8313-21423d2b40cb.png)
Looks cool, can't wait for Armor and Bows (and possibly arrows)! :)

**Comment by SigmundGranaas** [comment]
That's awesome man! There's a lot of work to do before I can start on Armour and bows, but arrows will definitely be included.
