### ISSUE TITLE
Update roadmap on curseforge and github

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#174]
Forgero has made a lot of developments recently, which means that the roadmap has changed significantly. This is not reflected on the curseforge page, or on GitHub where information is lacking.

## Roadmap
- Rework gems
- Implement a tool slot system
- Implement data driven custom tools and tool parts
- Separate Forgero core from Fabric
- Work on creating custom models for the tool parts.
- Balancing, bugfixing and small improvements.

## Upcoming features
- Bows, probably slated for 1.x
- Armour, probably slated for 1.x++

**Comment by SigmundGranaas** [comment]
CurseForge is updated

**Comment by JorisDeBeer** [comment]
Outdated I changed small bit on github
