### ISSUE TITLE
Redstone Ingot Alloy Support

### ISSUE THREAD

**Issue by ardissaps** [SigmundGranaas/forgero#178]
[Wired Redstone](https://modrinth.com/mod/wiredredstone) have add Redstone Ingot Alloy, would be great if can be included as one of the material (blade). No hurry.

**Comment by SigmundGranaas** [comment]
Are you looking to add redstone ingot as a material for creating tools when combined with wired redstone? Also, what stats do you think this materials should have when applied to tools?

**Comment by ardissaps** [comment]
I have no idea yet but mostly for looks (because of red), or maybe equal attack to copper but faster speed? Look like there is already red sword, please ignore if it is bad idea.

**Comment by SigmundGranaas** [comment]
Nah it does not hurt to create a config for redstone material if a mod adds to ingots. The config should be quick to add but I'll have to do it sometime later when I have time to look at it. Also, this might be a nice way to create "common" materials which will be enabled if different mods are loaded. Redstone ingots probably are not exclusive to only this mod.
