### ISSUE TITLE
All items in this mod have no texture.

### ISSUE THREAD

**Issue by addavriance** [SigmundGranaas/forgero#184]
Textures just dont exist. Maybe its a compatibility problem?
![image](https://user-images.githubusercontent.com/61160742/177157633-73f5a589-8668-48f8-817d-a7c27e164096.png)
![image](https://user-images.githubusercontent.com/61160742/177157643-5ede47b7-116f-48af-b353-d24d1fe499d1.png)

**Comment by SigmundGranaas** [comment]
Use Indium in addition to sodium. Does that resolve your issue or are the items still missing?

**Comment by addavriance** [comment]
Yup, now they're visible! But i didnt see that there was a mention of this mod in the mod docs..

**Comment by SigmundGranaas** [comment]
I recently added a line in the top of the introduction on curseforge, but yeah, the info should be more visible.
