### ISSUE TITLE
Smithee's Foundry Integration 

### ISSUE THREAD

**Issue by Balakay420** [SigmundGranaas/forgero#190]
Is there anyway you can integrate [Smithee's Foundry?](https://www.curseforge.com/minecraft/mc-mods/smitheesfoundry)

Would be fantastic if possible

**Comment by Balakay420** [comment]
It has a proper casting system from tinkers construct. In my mind, it would be great for the fabric community if you worked hand in hand together

**Comment by SigmundGranaas** [comment]
Compatibility would certainly be considered if feasible, I have no experience wit that mod as it seems to be quite fresh, but it looks promising. Currently I don't really have any time to work on integration, but I might be able to look at it after I have released the 0.10 update.

**Comment by JorisDeBeer** [comment]
discontinued
