### ISSUE TITLE
Some shaders are causing items to be rendered and behave incorrectly

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#194]
When using sodium, indium and iris, paired with a shaderpack like complementary shaders, tools can float in the hand of the player, which is accentuated when sprinting. In addition to this, the tool can poke through walls. This only happens when the shaderpack is enabled.

**Comment by DemonMartin** [comment]
Encountered same Issue with BSL Shaders, Iris + Sodium.

**Comment by SigmundGranaas** [comment]
Solved by removing dependency on Fabric rendering API for custom models. Will be solved #196.
