### ISSUE TITLE
crash caused by forgero

### ISSUE THREAD

**Issue by HixxyDubz** [SigmundGranaas/forgero#197]
modpack im using is DreamCraft, i added this mod in because i like it.

[crash-2022-11-03_17.59.06-client.txt](https://github.com/SigmundGranaas/forgero/files/9931892/crash-2022-11-03_17.59.06-client.txt)

**Comment by PenguinAlex** [comment]
same thing

**Comment by SigmundGranaas** [comment]
Is this issue present with the newest 0.10.1 version?

**Comment by SigmundGranaas** [comment]
Closing this as it is using an old version of Forgero
