### ISSUE TITLE
Support for QuiltMC mod launcher

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#215]
Adding support for quilt should not really be that hard.

**Comment by Steveplays28** [comment]
Forgero works perfectly fine for me on 1.19.2 Quilt, since Quilt supports Fabric mods.

**Comment by SigmundGranaas** [comment]
Oh, I never actually tested that, but that's awesome!

I still want to create a native implementation for Quilt to get know the ecosystem, in that case I can wait until Quilt matures some more.

**Comment by SigmundGranaas** [comment]
Reopen this issue if Forgero no longer works on Quilt, no time for native quilt implementation
