### ISSUE TITLE
[Suggestion] Please consider adding more language keys

### ISSUE THREAD

**Issue by Rad586** [SigmundGranaas/forgero#224]
Please consider adding language keys for _Head, Handle, Attributes, Primary and Durability_.
And it would be so kind of you to cancel the space in crafted tools' name. For example, 金 剑 is not equal to 金剑 in my language, it actually means gold&sword in English, which makes it sounds a little bit awkward.
And here's a screenshot of it.
https://i.postimg.cc/Dwm20k2M/S.png

**Comment by SigmundGranaas** [comment]
Hi! Thanks for your suggestion. I am about to release a new revamped version of this mod very soon, which will add new translation keys for mostly everything, although I am sure I have missed some words here and there. Feedback on parts i have missed is greatly appreciated and I will try to fix them as soon as possible. As 0.10 is releasing very soon, I won't spend any time going back to fix issues present in 0.9 and below, but I'll try to make the new version a lot more compatible with translations.

Regarding the space in the names, it's done to reduce the total amount of keys needed, but I get how that only applies in languages like english. It's sort of a hack, and I really should be autogenerating the whole keys instead of splitting them. Would it be easier for you if the tool's name was always derived from the translation key, like this: item.forgero.gold_sword, or would another format make it easier? Also, do you know if this process could be automated to generate a lot of the names in your language? All of the combination of parts, tools and materials would make the list of complete translation keys really long.

**Comment by Rad233** [comment]
> 

I think simply adding a space manually after the name of material while removing the auto-generated space could fix that. 
For example: 
  "item.forgero.gold": **"Gold"**, 👉  "item.forgero.gold": **"Gold "**.

 I'm not a programmer so I don't know if my idea works or not.

**Comment by Rad233** [comment]
> Hi! Thanks for your suggestion. I am about to release a new修改 version of this mod very soon, which will add new translation keys for mostly everything, although I am sure I have missed some words here and there. Feedback on parts i have missed is greatly appreciated and I will try to fix them as soon as possible. As 0.10 is releasing very soon, I won't spend any time going back to fix issues present in 0.9 and below, but I'll try to make the new version a lot more compatible with translations.
> 
> 关于名称中的空格，这样做是为了减少所需的键总数，但我明白这仅适用于英语等语言. It's sort of a hack, and I really should be autogenerating the whole keys instead of splitting them. Would it be easier for you if the tool's name was always derived from the translation key, like this: item.forgero.gold_sword, or would another format make it easier? Also, do you know if this process could be automated to generate a lot of the names in your language? All of the combination of parts, tools and materials would make the list of complete translation keys really long.

I think simply adding a space manually after the name of material while removing the auto-generated space could fix that.
For example:
"item.forgero.gold": "Gold", 👉 "item.forgero.gold": "Gold ".

I'm not a programmer so I don't know if my idea works or not.

**Comment by Rad586** [comment]
> Hi! Thanks for your suggestion. I am about to release a new revamped version of this mod very soon, which will add new translation keys for mostly everything, although I am sure I have missed some words here and there. Feedback on parts i have missed is greatly appreciated and I will try to fix them as soon as possible. As 0.10 is releasing very soon, I won't spend any time going back to fix issues present in 0.9 and below, but I'll try to make the new version a lot more compatible with translations.
> 
> Regarding the space in the names, it's done to reduce the total amount of keys needed, but I get how that only applies in languages like english. It's sort of a hack, and I really should be autogenerating the whole keys instead of splitting them. Would it be easier for you if the tool's name was always derived from the translation key, like this: item.forgero.gold_sword, or would another format make it easier? Also, do you know if this process could be automated to generate a lot of the names in your language? All of the combination of parts, tools and materials would make the list of complete translation keys really long.

I think simply adding a space manually after the name of material while removing the auto-generated space could fix that.
For example:
"item.forgero.gold": "Gold", 👉 "item.forgero.gold": "Gold ".

I'm not a programmer so I don't know if my idea works or not.

**Comment by SigmundGranaas** [comment]
I think I'll try to create new translatable separator element, which can simply be translated to "" if not required. Do you think that would work? If it does, it will be super simple to implement.

**Comment by Rad586** [comment]
> I think I'll try to create new translatable separator element, which can simply be translated to "" if not required. Do you think that would work? If it does, it will be super simple to implement.

I think that works.

**Comment by SigmundGranaas** [comment]
It is already updated in the latest version, so you'll have to see if there still are some missing keys, or if the new separator causes any translation issues.

**Comment by Rad586** [comment]
0.10.4.1 is missing loads of things(like duelling guard, reaper head...) that doesn't appear in en_us.json.

**Comment by SigmundGranaas** [comment]
Most of the content related stuff is kept in different modules. Forgero-vanilla contains material and part translations, Forgero-extended contains gem and extended part translations and Forgero-compat contains translations for different compatabilities, like MM.

**Comment by Rad586** [comment]
Sorry for spamming! I forgot merging them together..

**Comment by SigmundGranaas** [comment]
No worries, I'll just merge them all
