### ISSUE TITLE
Forgero 0.??: Gems 

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#232]
## Gemsupdate
I changed the name to Gems to make it a bit more specific. Basically we had big plans, most of the soul stuff I will no reorganize this issue to make it more clear what we want and how we want it. All stuff that is postponed (I think) I will keep underneath all other stuff so I dont delete it for no reason. 

## Gems update
Our new plans with gem update are to basically create specific stats boost for all tools. Special abilities etc will come later on in a form of artifacts.

Currently this is the idea for the gems: 
Amethyst will boost Mining level
Diamond will boost Durability
Echo will boost Mining speed
Prismarine will boost Attack damage
Emerald will boost Attack Speed
netherquartz will boos tArmor
lapis will boost Reach

Each gem will have 5 levels with stats increasing every level. Last two levels of the gem will be animated. 

Crafting process / upgrading process isnt really decided on yet. Could use nether star in it? 

# OLD GEMS & TRINKETS
- [ ] #310
- [x] #309
- [x] #307
- [x] #308
- [x] #311
- [x] #312
- [ ] Introduce gem shaping
- [x] #314
- [x] #363
- [ ] End stone gem

## Gem mechanics
- [ ] Different gem bases
- [x] Tracking player statistics
- [ ] Level limits and restrictions
- [ ] GLINTGLINTGLINTGLINT ON TOOLS GLINTGLINT

## Souls
- [x] #328 
- [ ] Create models and textures for different soul types
- [x] #365
- [x] #360
- [x] #371
- [x] #356
- [x] Create tooltip info for gems
- [ ] Create the soul binding ritual
- [x] #373
- [x] #372 
- [ ] A pedestal which can display weapons and their souls statistics

## New mobs
- [x] #260
- [ ] Crystalized zombie
- [ ] Crystalized skeleton
- [ ] Ender-eyed shulker
- [x] #315

## New stations
- [ ] Altar / shrine ( Soul binding )
- [ ] Gem station ( Gem basing and upgrading )
- [ ] Gem cutter ( Shaped gems )

## Attributes and properties
- [x] #346
- [x] #349
- [x] #348
- [x] Mob specific damage boosts

**Comment by Steveplays28** [comment]
Might be worth updating this and merging #101 into this.

**Comment by JorisDeBeer** [comment]
### To Do List First Iteration Gems

- [ ] Add reach in the tooltip 
- [x] Add remaining recipes
- [x] Add loottable 
- [x] Remove "level 1" naming problem on gems

**Comment by JorisDeBeer** [comment]
I close this as its been mostly done if we wanna bring it back we can with animated gems sometime
