### ISSUE TITLE
Forge support

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#268]
Work on experimental support for the Forge modloader.

**Comment by SigmundGranaas** [comment]
Forge support has hit a momentary stop, as I have to figure out a way to include the minecraft-common library with Architectury-loom. There's a lot to learn about gradle and packaging before I can make that work.

**Comment by JorisDeBeer** [comment]
Can we just wait for 1.21 and use connector as its actually setting up to be a really stable api?

**Comment by SigmundGranaas** [comment]
Yeah I agree, it's probably better to rely on Syntra for the time being.
