### ISSUE TITLE
Bug: Attempt to break the assembly station in survival mode breaks only one block.

### ISSUE THREAD

**Issue by Golemosus** [SigmundGranaas/forgero#274]
Only Forgero installed. Version 0.10.2. minecraft 1.19.2.
Attempt to break the assembly station in survival mode breaks only one block.
Breaking the left side first causes the right side to become invisible, retaining it's collision box.
Breaking the right side first makes it lose it's collision box, yet the model is still visible.
The remaining side can be broken with no issues.

**Comment by SigmundGranaas** [comment]
Multi block structures is a mess, very likely that I have messed up the rotation of the block connection when destroying one part of the table. I will try to replicate it and see which direction causes incorrect breaking behaviour.
