### ISSUE TITLE
Oversight: Same attributes of refined and mastercrafted pickaxe heads.

### ISSUE THREAD

**Issue by Golemosus** [SigmundGranaas/forgero#275]
Only Forgero installed. Version 0.10.2. minecraft 1.19.2.
Refined and mastercrafted pickaxe heads share the same attributes.
Occurs with all materials (expectedly), only with pickaxe heads (hoes follow expected progression).
Those attributes are also set to lower values than in basic rarity level counterparts.

**Comment by SigmundGranaas** [comment]
Yeah that's definitely an oversight, luckily it's easy to create proper configurations
