### ISSUE TITLE
Performance(?): Compatibility with other mods appears to register items even if said mods are not present.

### ISSUE THREAD

**Issue by Golemosus** [SigmundGranaas/forgero#277]
Custom modpack (doubt it's relevant). Forgero 0.10.2. minecraft 1.19.2.
My server log displays those massages even though mythicmetals and wired redstone are not present:
[03:08:17] [main/INFO]: Registered wired-redstone-materials
[03:08:17] [main/INFO]: Registered mythicmetals-materials
Effect on load times is probably minimal, but bundled with other optimization issues it might become relevant.

**Comment by SigmundGranaas** [comment]
It's actually only registering the pack as present, but it should also say that the packs are disabled cause the mods are not present. It never actually processes the resources into items. Although I should probably just remove all mentions of disabled packs, and keep it at a Debug log level.

As for the performance, I recently switched to async loading of the forgero packs in the Forge branch, so when it gets merged, all pack loading will be done asynchronously and the resource loading process will only be restricted by the pack that takes the longest to load, as opposed to loading each pack in sequence.

Still I believe I could do some more optimization on the disabled packs to reduce load times.
