### ISSUE TITLE
[bug]Connection error in logging to server with Roughly Enough Resources

### ISSUE THREAD

**Issue by suquiya** [SigmundGranaas/forgero#278]
Internal Exception throws forgero + rer(Roughly Enough Resources) modded surver with forgero+rer installed clients.

minecraft version: 1.19.2
fabric version: 0.14.12
fabric server launcher version: 0.11.1
mods: forgero + rer and rer dependencies (I tested with curseforge client and install with curseforge client).

I made that the server and client have same mod configuration by copy and paste with sftp.
I removed either of two, this error did not throw.

Client displays:
```
Connection Lost
Internal Exception: java.net.SocketException: Connection reset
```
I searched logs, but I cannot find about this error.

Server Logs below:
https://gist.github.com/suquiya/c7732c26aca41f2aad72c229a5158139

**Comment by SigmundGranaas** [comment]
Interesting issue. I haven't tried RER, but I'll give it a go to see if I can replicate the exception. No idea what's going on here, but thanks for submitting the issue!

**Comment by SigmundGranaas** [comment]
Issue was solved by moving to a static initializer for the gem level loot function.
