### ISSUE TITLE
Tooltip causing crash and also breaking REI mod's search bar.

### ISSUE THREAD

**Issue by ItzNatsu** [SigmundGranaas/forgero#285]
Hovering over any part item in the game causes the game to crash. REI's search bar also completely breaks for some reason because of that. mods like Item Borders, which utilizes the tooltips information to give the items a border for the rarity causes any container with parts in them to crash the game. disabling Item Borders allows opening the containers, but hovering over the item crashes the game. this issue is happening on version 0.10.2-BETA-1.19.2 version of the mod. I will attach 3 different crashes related to each mod mentioned. all are caused by forgero. 
[ItemBorders_Crash.txt](https://github.com/SigmundGranaas/forgero/files/10340928/ItemBorders_Crash.txt)
[REI_Crash.txt](https://github.com/SigmundGranaas/forgero/files/10340929/REI_Crash.txt)
[Crash.txt](https://github.com/SigmundGranaas/forgero/files/10340930/Crash.txt)

**Comment by ItzNatsu** [comment]
Found a fix. i read more into the error and it seems that it is a locale issue. some countries use different decimals format. it seems the way your mod is coded doesn't support all types of formats. simply changing my region in settings and restarting my computer fixed it.

**Comment by SigmundGranaas** [comment]
Thanks for the issue! Which languages causes this issue?

It seems that the code that handles numbers just assumes it can easily be cast to floats, but that's not the case here. Luckily that's going to be fairly simple to fix.

**Comment by SigmundGranaas** [comment]
It seems at least Ukrainian causes this issue, so this problem might be present with languages that use cyrillic symbols.

**Comment by SigmundGranaas** [comment]
Issue has been fixed by moving to a decimal formatter that uses localized settings. Will merge the fix when I get home.
