### ISSUE TITLE
Crash: Non [a-z0-9/._-] character in path of location: forgero:forgero_guide_book_recipe_forgero:bindings

### ISSUE THREAD

**Issue by Mg138** [SigmundGranaas/forgero#293]
version: forgero-fabric-full-0.10.4-BETA-1.19.2.jar

**Comment by SigmundGranaas** [comment]
Seems like there's a typo in the patchouli guidebook recipe generator. I'll upload a patched version and set up a Gametest to run on the compat module to catch these errors.
