### ISSUE TITLE
Reduce logging output by creating a silent config option on the resource pipeline

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#295]
It should be possible to to silence pipelines to make them produce 0 logging output, or at-least change it to debug only with the context that this is running from a resource reloader and should produce less output.

Ideally the configurations should look like this:

```
PipelineBuilder.builder()
                        .silent()
                        .register(() -> config)
                        .register(FabricPackFinder.supplier())
                        .state(ForgeroStateRegistry.stateListener())
                        .register(availableDependencies)
                        .build()
                        .execute();
```

**Comment by Steveplays28** [comment]
Pretty sure this is implemented already with the `resourceLogging` config option

**Comment by SigmundGranaas** [comment]
I should have specified that this is mainly intended to target the pipelines that run in the resource reloaders to make it possible to update resources from data packs. No need to print that 17 packages were loaded 3 times, because I believe that's how many times it will run before loading the world.

**Comment by Steveplays28** [comment]
Ah alright, should be a relatively easy fix then
