### ISSUE TITLE
Infinite durability with assembly station

### ISSUE THREAD

**Issue by DailyEffortBird** [SigmundGranaas/forgero#305]
Tools can be broken down into their individual parts when at low durability at an assembly station and immediately put back together to restore durability.
The ingame books says that only tools with 100% durability can be disassembled but I've tested it and this is incorrect.

Using Forgero 10.4.1 for 1.18.2 on Fabric

**Comment by SigmundGranaas** [comment]
That's a pretty big oversight. I'll see what changed that broke the durability check. Hopefully it's only present on 1.18.2

**Comment by SigmundGranaas** [comment]
Seems like it's present on all versions

**Comment by SigmundGranaas** [comment]
Fixed and added a test to assert this cannot happen
