### ISSUE TITLE
Dragon eye gem

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#307]
Create the new dragon eye gem.

Can be crafted by combining a dragon eye with a gem base.

grants damage bonus against ender creatures

- [x] Create the dragon eye texture
- [ ] Add the dragon eye to a loot table
- [ ] Create the dragon eye gem resource
- [ ] ender create specific damage

**Comment by JorisDeBeer** [comment]
Outdated
