### ISSUE TITLE
Duplication glitch with Assembly Station

### ISSUE THREAD

**Issue by Mg138** [SigmundGranaas/forgero#316]
If you shift click the resulting items, the input doesn't get removed.

Someone probably missed the handling of shift clicking, since those count as different methods IIRC.

**Comment by SigmundGranaas** [comment]
Woopsie, I'll get that fixed

**Comment by SigmundGranaas** [comment]
@Mg138 Could you show me a screenshot or something similar of this happening? I can't replicate it on my end. Also, which version are you using?

**Comment by Mg138** [comment]
Was using whatever the latest was until we tried to update.

Will try to use a working version to test it.

**Comment by Mg138** [comment]
Sigh, tried to downgrade, spent a lot of time to finally find a working version, and then it didn't actually load the items in.

We're too exhausted to figure this out now, maybe this is already fixed in the newer versions (if they would run on my machine)

Closing this unless we try it some time later and still have dupe bug.
