### ISSUE TITLE
Allow crafting schematics

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#317]
It'd be nice if you could allow creating schematics using tool parts and paper, instead of having to find them all as loot drops.
This way, you could replace vanilla tools completely like in Tinker's Construct.
I can kind of do this using CraftTweaker/KubeJS, but it's quite a hassle, and doesn't show up properly in EMI.

And having an option to disable vanilla/modded tool recipes in favor of Forgero tools (or maybe a better solution would be to set vanilla/modded tools' durabilities to 1, like Tinker's Construct could do) would be nice.

I'd really love to use this in a full survival playthrough without normal tools with some friends, and get a Tinker's Construct 1.7.10 like experience.
I'm up to help if wanted!

**Comment by SigmundGranaas** [comment]
Hiya! 
Crafting schematics from parts is a supported feature, but there might have been some issues with the recipes in the currently released version. The issue has been fixed, and every schematic should be craftable with paper + tool, when 0.10.5 releases sometime soon. I am considering changing the schematic system, to only make basic schematics craftable with normal paper, while introducing another mechanic for crafting higher tiered schematics. I am still not sure what the best approach is, so I'll keep it like this until I have a concrete plan.

I have considered creating a settings toggle that can disable/hide normal tools, but haven't prioritized it yet. It should not be too hard, so I might include this with 0.10.5 when it releases. I have been pretty cautious when it comes to making changes to tools from vanilla/other mods, in case it causes compatibility issues, or breaks normal features, but if its an opt-in feature I think it would be a nice addition. If you would like to help me test this feature, that would be awesome, and I could experiment with different implementations.

To disable recipes, I can add two entries to the config file, one is a toggle to disable selected recipes, and the other is a list with recipe identifiers that we would like to disable. I'll test if setting the durability to 1 is simple to add, and if so, I can add the feature behind a configuration toggle.

**Comment by Steveplays28** [comment]
Hey, that's cool, thank you!
It definitely isn't letting me craft schematics from parts, though I might be running a bit of an outdated version, glad to hear that's been fixed.

Making the changes to normal tools (be it vanilla or modded), should definitely be opt-in, I agree.
I don't mind testing!

For the higher tiered schematics, maybe have something like Tinker's Construct's smeltery + metal casts?
Though it might be easier integrate with Alloy Forgery or Smithee for the smeltery, if you plan to go that route.

**Comment by SigmundGranaas** [comment]
Integrating some form of smeltery is definitely an option, but its still far off, so I won't lock in any decision yet. Its probably a matter of figuring how much time I have for development of the features, and what makes the most sense gameplay wise. I am still looking for great ideas, so if you want to take part in the discussion, be sure to join the Discord.

I'll try to see if I can get something done tonight regarding the disabling of vanilla tools. The issue has been up for a long time, so it would be great to get it resolved. See #155

**Comment by Steveplays28** [comment]
Alright, thanks! Will take a look at the Discord server then. Good luck with it!

btw, the invite link to the Discord on Modrinth is expired. Works on CurseForge though.

**Comment by SigmundGranaas** [comment]
Updated the link now

**Comment by Steveplays28** [comment]
Ay nice!
