### ISSUE TITLE
Repair kits not working

### ISSUE THREAD

**Issue by DailyEffortBird** [SigmundGranaas/forgero#320]
Made three separate repair kits matching the materials used in the head and handle and none worked.
![image](https://user-images.githubusercontent.com/122572140/212602801-cb74947d-49a4-4def-8cab-50a2944afd7d.png)
![image](https://user-images.githubusercontent.com/122572140/212603311-14247d78-3937-493c-b4df-0ca6a4fd432c.png)

**Comment by SigmundGranaas** [comment]
It seems like the recent update broke basically every recipe. It should be an easy fix to get it working, so I'll bundle it with 0.10.5, and add another Gametest to make sure it works in the next versions as well.
