### ISSUE TITLE
Crafting recipe for wooden sword guard and bowl is the same

### ISSUE THREAD

**Issue by DailyEffortBird** [SigmundGranaas/forgero#342]
The mod "polymorph" lets me switch between conflicting identical crafting recipes so this isn't an issue but it can be for people without the mod.

**Comment by SigmundGranaas** [comment]
Oh, I didn't think about that. Thanks for the heads up! I'll see if I replace the recipe with something else. Do you by any chance have a good idea?

**Comment by DailyEffortBird** [comment]
![image](https://user-images.githubusercontent.com/122572140/213944169-9a8a20f1-9712-45b7-b193-06097ed427e9.png)
Maybe something like this.

**Comment by SigmundGranaas** [comment]
Didn't think about integrating slabs into the recipes, that's actually a good idea!
