### ISSUE TITLE
Fix pattern mining being able to mine non-handled blocks

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#375]

**Comment by Steveplays28** [comment]
I believe wood (instead of logs) isn't registered, which causes the pattern mining tools not to work sometimes on trees that have both logs and wood.

**Comment by SigmundGranaas** [comment]
I will add that to the vein mining tag as well 👍

**Comment by Steveplays28** [comment]
Thanks!
