### ISSUE TITLE
Add support for custom configuration options

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#38]
I need to look into ways of parsing configuration options. This will allow me to configure:

- [ ] Choose which palettes will be generated and which will be picked up from a file, or any other source.
- [ ] Choose which textures should be generated automatically and which have hand made textures
- [ ] enable and disable certain items/gems/tools/toolparts
- [ ] additional stuff

Related to #158

**Comment by Steveplays28** [comment]
Related to #10, might want to merge these two issues.

**Comment by SigmundGranaas** [comment]
I think I'll close this issue, as it does not mention anything special that needs to be added, and everything else is sortof implemented so this issue is largely just outdated.
