### ISSUE TITLE
Create an Item container that allows you to place items in the work in different poses

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#383]

**Comment by JorisDeBeer** [comment]
what?

**Comment by SigmundGranaas** [comment]
Don't question it

**Comment by JorisDeBeer** [comment]
close or?

**Comment by SigmundGranaas** [comment]
NOOOOOOO
Okay maybe

**Comment by JorisDeBeer** [comment]
I dont even understand what you mean with the title lol

**Comment by JorisDeBeer** [comment]
Just a cosmetic block that has a inventory and a renderer?

**Comment by SigmundGranaas** [comment]
It was to be able to create structures with in-world items. Like an axe embedded into the table or something.

**Comment by JorisDeBeer** [comment]
bye
