### ISSUE TITLE
Support for the Graveyards mod

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#384]
Integrate with graveyards loot table to add soul reaping parts, as well as integrate the soul binding ritual with their altar. For 0.11.

**Comment by Steveplays28** [comment]
What exactly do you mean by support for The Graveyard?
Currently running both Forgero and The Graveyard on my server, haven't noticed issues of any kind (yet).

**Comment by SigmundGranaas** [comment]
There, I updated the issue with some more info. The issue is mostly focused on content integration

**Comment by Steveplays28** [comment]
Ah, that's super cool! Thanks.

**Comment by JorisDeBeer** [comment]
#211
