### ISSUE TITLE
Multipart blocks can't be placed next to grass

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#387]
![Assembly station can't be placed next to grass](https://media.discordapp.net/attachments/981828752659083267/1070035642555310181/image.png)
> Can't place an assembly station at the pointed block because of the grass!

Multipart blocks can't be placed next to grass, flowers, dead bushes, etc.
Though it does work the other way around (you point at grass and there's air next to it).

Would be a nice convenience to be able to place multipart blocks next to them.

**Comment by SigmundGranaas** [comment]
Fixed so yo can place the assembly station next to any non-solid block.
