### ISSUE TITLE
`#forgero:schematic` tooltip is too big to fit on the screen

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#393]
![image](https://user-images.githubusercontent.com/62797992/216774400-dbc489df-2762-4ee9-8c05-09119bcf597b.png)
No clue what this schematic recipe is called, but it can be viewed from the Assembly Station recipe with EMI.

EDIT:
It appears to be the tooltip of `#forgero:schematic`. Viewed with GUI scale 1 (lmao):
![image](https://media.discordapp.net/attachments/981828752659083267/1071445929732886558/image.png)

**Comment by JorisDeBeer** [comment]
Just tested seems fixed
