### ISSUE TITLE
Early game smithing table

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#394]
It would be neat if there was a way to upgrade wooden tools to stone (and stonelike blocks) without having to grab paper from somewhere.
So like a smithing table, but early game.

**Comment by SigmundGranaas** [comment]
It's possible to create a recipe for this in the crafting table. Maybe surround a tool part with three stone-ish blocks and it will turn it into a stone version of the tool

**Comment by SigmundGranaas** [comment]
![image](https://user-images.githubusercontent.com/46557903/216813338-7d331c1a-80a3-4102-aba7-4476cb227a99.png)

**Comment by SigmundGranaas** [comment]
I implemented this to work for all types of tool parts. It makes no sense to upgrade like a vein mining pickaxe head to a simple stone one, but now you can at least

**Comment by SigmundGranaas** [comment]
I haven't done a 1-1 upgrade, simply to avoid recipe implosion. If I were to register an upgrade recipe for every part for all of the stone variants, there would be a lot of unnecessary upgrades for such a simple use case.

**Comment by SigmundGranaas** [comment]
![image](https://user-images.githubusercontent.com/46557903/216814291-a828b190-a9d3-4aaf-8ac8-b68817d045f9.png)
That's about right I suppose

**Comment by Steveplays28** [comment]
Awesome, looks good!
