### ISSUE TITLE
Remove vanilla tools from loot generation if the `disable_vanilla_recipes` config option is set

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#396]
![image](https://media.discordapp.net/attachments/981828752659083267/1071452928713433188/image.png)
Vanilla iron pickaxes still generate in blacksmith chests, for example, even though the `disable_vanilla_recipes` config option is set.

**Comment by SigmundGranaas** [comment]
The option to disable recipes is quite, specific, should we maybe add an option like `disable_vanilla_tool_loot` ?

**Comment by Steveplays28** [comment]
Sounds good, though maybe it'd be less confusing if there was simply a way to do both in one option like `disable_vanilla_tools`.

**Comment by SigmundGranaas** [comment]
Yeah that would be a lot simpler to toggle.

**Comment by SigmundGranaas** [comment]
I am adding a toggle that changes the loot to forgero loot as well.

**Comment by Steveplays28** [comment]
Ayy nice!
