### ISSUE TITLE
Add GUI widgets for all remaining primitive types

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#397]
Currently only `Boolean`s and `List<String>`s have GUI widgets created for them, so new config options using different types like `Integer`s will be missing from the config screen,

**Comment by SigmundGranaas** [comment]
Oh shit, it has to be made scrollable as well for any more settings to be added. It seems like the only option is to implement the whole thing as a scrollable list, then.

**Comment by Steveplays28** [comment]
Yup, shouldn't be too hard of a change though.
Will also have to redo the GUI widgets for the booleans and lists to use a class instead of a function at some point

**Comment by SigmundGranaas** [comment]
Yeah I saw the Todo's and promptly ignored them. I had a look at how modmenu did their scrollable widgets and just thought nope, not today...

**Comment by Steveplays28** [comment]
We switched to [YACL](<https://modrinth.com/mod/yacl>), this is no longer relevant.
