### ISSUE TITLE
Mod menu configuration screen runs out of vertical space to place all options

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#416]
![image](https://user-images.githubusercontent.com/115664543/218056476-b7a09ff6-19db-4351-8fec-4edd6911dc26.png)

**Comment by SigmundGranaas** [comment]
Yeah the mod menu is a bit of a mess untill we add a scroll container. See issue #397

**Comment by Steveplays28** [comment]
mb hahaha

**Comment by SigmundGranaas** [comment]
No worries, we both knew this would happen when we would add more config options

**Comment by Steveplays28** [comment]
Yep. Will fix soon:tm:
