### ISSUE TITLE
Parts made with (new) schematics don't show proper value

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#417]
![2023-02-10_10 38 30](https://user-images.githubusercontent.com/115664543/218057603-f8ce92f2-cde4-4fa3-b661-29f9d7b3610b.png)

/ 

![2023-02-10_10 38 46](https://user-images.githubusercontent.com/115664543/218057668-24757132-f87b-4c57-8016-31f83dffb438.png)

This is with all the new schematics. Wooden variants (the new added wood of the nether)only shows attackspeed (see picture). 

![2023-02-10_10 41 53](https://user-images.githubusercontent.com/115664543/218058277-5d9cd7a8-7a69-4f61-90a3-480363a7d4d6.png)

**Comment by SigmundGranaas** [comment]
It's possible I have forgotten to add an attack damage scaler for the wooden variants, I'll look into it further!
