### ISSUE TITLE
Vines show item.forgero.vines

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#418]
![2023-02-10_10 47 34](https://user-images.githubusercontent.com/115664543/218059527-e08dc619-52b1-4f01-936f-939f3bb002db.png)

**Comment by JorisDeBeer** [comment]
And wrong texture I guess?

**Comment by SigmundGranaas** [comment]
Yeah I I have forgotten translations and probably did a dirty copy when making the vine material palette. Should be easy to fix.
