### ISSUE TITLE
Add config option to allow smelting tool parts

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#419]
Being able to smelt/blast tool parts (and maybe even Create bulk blasting) would be super neat.
Also having a config option to disable disassembling tool parts into 1 of the tool part's material would be cool to have as well.

**Comment by SigmundGranaas** [comment]
That's a good idea! I don't think it needs to be locked behind a config setting, though. I think this should be default behaviour.

**Comment by Steveplays28** [comment]
That's fine too! It does make a lot more sense.
I had 3 people try to smelt the tool parts in my server, me included, only to figure out that you need to disassemble them.

Don't forget to make it work with a blast furnace as well. Create bulk blasting would be neat as well but idk if that's a lot of work

**Comment by SigmundGranaas** [comment]
I'll create a recipe generator for furnaces as well as blast furnaces. It should work on every metal, right?

**Comment by Steveplays28** [comment]
Yup! Not sure if stone tools and tool parts should also be smelted to stone though.
Do wooden tools and tool parts work as fuel btw?

**Comment by SigmundGranaas** [comment]
I have never tested them as fuel, so probably not. I could probably do that within itemsettings, so I suppose its an easy implementation

**Comment by SigmundGranaas** [comment]
I'll probably skip stone at this point, as I don't really want to deal with the cobble to stone part quite yet. The system can easily handle smelting to its root material, but smelting to another material, would require manual overrides.

**Comment by Steveplays28** [comment]
Fair enough, no worries
That's for a future PR/update then

**Comment by SigmundGranaas** [comment]
Yeah the real challenge would be to implement it in a non-hacky way, so that's probably a future challenge

**Comment by SigmundGranaas** [comment]
Unfortunately, smelting recipes can only yield 1 of each item, makes it less useful.

**Comment by Steveplays28** [comment]
That's alright. Makes it a tradeoff.
