### ISSUE TITLE
Weird texture bug when putting trinket into a sword guard.

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#423]
Happens with the normal sword guard template that has been upgraded with a material. When adding the trinket textures just disappear. Tested this with multiple different resources and trinkets. 

![image](https://user-images.githubusercontent.com/115664543/218255669-fed8b7c6-69b7-435b-83ce-1e6ceed9ef53.png)

**Comment by SigmundGranaas** [comment]
Does this happen with vanilla materials, or only material added in a custom pack? I tried to replicate it, but I showed up fine for me with vanilla materials

**Comment by JorisDeBeer** [comment]
Hmm, happens for me with everything. Tried it with only oak wood but gave the same result.

**Comment by SigmundGranaas** [comment]
Right, I had it happen to me randomly. Hopefully its caused by ambiguity in the sword guard model definition.
