### ISSUE TITLE
Crash with `0.10.7-rc2`

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#432]
## Version info

- Minecraft `1.19.2`
- Forgero `0.10.7-rc2-BETA-1.19.2`
- Quilt `0.18.1-beta.59`
- QSL `4.0.0-beta.27` (provides Fabric API `0.73.0`)

## Log

```log
org.quiltmc.loader.impl.FormattedException: java.lang.NullPointerException: Cannot invoke "com.sigmundgranaas.forgero.core.type.TypeTree.find(com.sigmundgranaas.forgero.core.type.Type)" because "com.sigmundgranaas.forgero.core.ForgeroStateRegistry.TREE" is null
```

**Comment by SigmundGranaas** [comment]
I make quite a few calls the the typetree around the codebase which really should not happen. I guess this issue would fit well with rewriting the typetree functionality behind a better interface. Directly referencing it should happen through a service of some sorts to prevent nullpointers like this from happening.

**Comment by SigmundGranaas** [comment]
Issue comes from the fact that The Fuel time map is created before Forgero is initialized. I don't really know why this happends, but it means that Forgero won't support burning parts as fuel on Quilt.

**Comment by Steveplays28** [comment]
Alrighty, thanks for fixing the issue though, even if you had to remove functionality.
