### ISSUE TITLE
Too many (3) achievements are given at once when making a tool part

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#435]
![image](https://user-images.githubusercontent.com/62797992/218318076-cc6a95bb-a067-4f33-a607-f9fecca1cb89.png)

**Comment by SigmundGranaas** [comment]
I will probably include this in a bigger issue to rework the achievements. I won't bother touching them too much when I have planned to completely rework the in the bearish future

**Comment by Steveplays28** [comment]
I'll incorporate a few into my other issue #433

**Comment by JorisDeBeer** [comment]
Is fixed in current build because I removed them oops
