### ISSUE TITLE
Assembly station automatically disassembles tool on putting it in. 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#436]
So putting the tool in and backing out (without taking anything) midway drops all the resources. Dont know if its intended, but for someone that just wants to see what he gets back and then backing out its not that handy.

**Comment by SigmundGranaas** [comment]
Alright, I'll make it so that it drops the original tool if it's still present in the input box. If there is nothing in the input box then the crafting inventory will be dropped.
