### ISSUE TITLE
Duplicate content roots detected (IntelliJ)

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#437]
![image](https://user-images.githubusercontent.com/62797992/218341458-0f5fdde9-8aad-4796-bce2-914e422f2cdc.png)
> Duplicate content roots detected: Path [D:/Repos/forgero/forgero-vanilla/src/main/resources] of module [forgero.forgero-extended.test] was removed from modules [forgero.forgero-vanilla.main]

**Comment by SigmundGranaas** [comment]
Intellij does not support attaching multiple roots in multi module systems yet, that's why it's giving a warning, but this is a valid grade use case so it works as intended

**Comment by Steveplays28** [comment]
Good to know, slightly bugs me every time I open the Forgero project haha 😅

**Comment by SigmundGranaas** [comment]
Yeah it's really anoying

**Comment by Steveplays28** [comment]
We can't do much about this then
