### ISSUE TITLE
Reinforcement in handles glitches through sword guard. 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#444]
![2023-02-13_22 47 44](https://user-images.githubusercontent.com/115664543/218582378-f75964bd-0157-4b45-8551-807968a49f2b.png)

When using a handle with reinforcement for swords it glitches through the guard.

**Comment by SigmundGranaas** [comment]
I have probably set the layer priority too high for the reinforcement model on the handle,I'll look into it

**Comment by SigmundGranaas** [comment]
It seems this only happens with textures that have been relocated using offsets. That's interesting!

**Comment by SigmundGranaas** [comment]
Fixed in #450
