### ISSUE TITLE
All axe heads exept for the base one don't show reinforcements

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#451]
![image](https://user-images.githubusercontent.com/115664543/219433840-cf715291-8527-43d9-a300-45d213e7cdfa.png)

**Comment by SigmundGranaas** [comment]
That is wierd, I didn't find anything obvious in the configs, so I'll have another look later.

**Comment by SigmundGranaas** [comment]
Lol, all of the axe models had the wrong order.
