### ISSUE TITLE
Parsing error with adding new woods

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#454]
![image](https://user-images.githubusercontent.com/115664543/219480659-41b1d317-bb5f-4f0c-9643-96988f855d4d.png)

I thought we had patched this already? Or is that in the next release? 

It still searches for its minecraft wood variants that dont actually exist.

**Comment by JorisDeBeer** [comment]
only gives errors with recipes, so I suppose its different from the last time?

**Comment by SigmundGranaas** [comment]
This is indeed different from last time. I couldn't find exactly how this would happen, so I would probably ask to see the pack which create this issue so I can debug it. Also, make sure the namespace used for the resource is not actually set to minecraft.

**Comment by JorisDeBeer** [comment]
I mean, what issue? Who even posted this? pfff

**Comment by SigmundGranaas** [comment]
Damn, these issues really seem to close themselves
