### ISSUE TITLE
0.10.7 Release

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#455]
0.10.7 has been a shitshow, and should be released as fast as possible. The RCA's has showed that a lot of stuff needs to be patched before this release is ready for primetime.

These are the issues that needs to be fixed before it's ready for release:
- [x] #164 
- [x] #409 
- [x] #432 
- [x] #431 
- [x] #456
- [x] #416
- [x] #481 
- [ ] Might look into building and releasing artifacts for this version, but that's only if I have time.

There are a lot more issues that needs work, but these are the most critical ones.

**Comment by JorisDeBeer** [comment]
Maybe also the balancing with the structure rewrite of the materials?

**Comment by SigmundGranaas** [comment]
That's a good idea, hopefully the new tooltips will make that easier

**Comment by SigmundGranaas** [comment]
Do you want to create a draft for how the materials should be changed or should we do it together?

**Comment by JorisDeBeer** [comment]
Hmm, why dont I try to make something with the newly made documentation on attributes? Then I can share it for feedback etc. Its a good test for me, for the system in general and for the newly made documentation.

**Comment by SigmundGranaas** [comment]
That would be really neat! Also feel free to come with suggestions for new ways of structuring materials/new attributes and properties, that you think are good additions, or make the properties easier to manage.

**Comment by SigmundGranaas** [comment]
I created an issue #473 

I won't add this to 0.10.7 yet, as I don't know how long it will take to complete this task, and I don't want to keep the update if we can't finish this quickly. I really prefer frequent updates

**Comment by Steveplays28** [comment]
Might be worth saving for `0.11` instead since it'd change a lot about existing Forgero tools

**Comment by SigmundGranaas** [comment]
That's true, it's possible to point it straight to the 0.11 branch if we want to start work early.

**Comment by Steveplays28** [comment]
Speaking of branches, we need to clean up the ones that are no longer in use and got merged already

**Comment by SigmundGranaas** [comment]
Oooh, that's true, haven't kept up with the branches in a long time

**Comment by SigmundGranaas** [comment]
Most branches that haven't been touched for months (Except bow&arrow) can probably be deleted

**Comment by SigmundGranaas** [comment]
Damn you're going to create an issue for it aren't you?

**Comment by Steveplays28** [comment]
hehe, yes
