### ISSUE TITLE
Add patchouli documentation for conditions

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#456]
Add an entry to the patchouli guidebook explaining what conditions are and how they can be found on looted components. The system is dynamic, so it's not necessary to list out every single available conditions, just a couple.

**Comment by JorisDeBeer** [comment]
I could help with this if you give me some pointers!

**Comment by SigmundGranaas** [comment]
Here's the general wiki for writing guidebooks: https://vazkiimods.github.io/Patchouli/docs/patchouli-basics/getting-started/

The Guidebook data pack is currently in the forgero-fabric module: data/forgero/patchouli_books/forgero_guide

My guidebook is split into different parts which are intended to be shipped with the different content modules, but a bug in patchouli in preventing that for the moment. The only relevant here is the forgero_guide book, it's the main one.

I think adding a separate category for conditions would be nice, or it could be included in a category about loot in general. If it's included with loot info, it can explain how different tiers of loot is found in different chests in the world as well.

I don't think the conditions system needs a whole lot of text, just a page or two detailing that different conditions can apply to different types of parts/schematics, and that the different conditions gets more rare the better it is. There are generally a couple of tiers of conditions per stat. 

It might be nice to look at the conditions wiki page for reference, but no need to get too technical. 

A couple of examples of different conditions might be nice, as well as how rare they are. For reference, all conditions are in the forgero-vanilla/data/forgero/conditions.

The chance property decides how rare they are, and is a number between 0-1. 0.10 means a 10% chance that the condition will apply when looted from a chest.

**Comment by SigmundGranaas** [comment]
It would be nice with either a picture of the condition in the tooltip, or a spotlight page with the nbt of a tool with a condition. I can supply you with the stringifyed item + nbt tag of you want some spotlight pages.

To test out the conditions system, just generate a ton of loot using the command /loot spawn ~ ~ ~ loot minecraft:chests/end_city
( Command might be a little off, can't remember exactly from the top of my head )

**Comment by SigmundGranaas** [comment]
Here are some nbt strings:

id: "mangrove-mastercrafted_hoe_head"
nbt: "{FORGERO:{COMPOSITE_TYPE:"SCHEMATIC_PART",CONDITIONS:["forgero:quick"],ID:"forgero:mangrove-mastercrafted_hoe_head",INGREDIENTS:[{ID:"forgero:mastercrafted_hoe_head-schematic",NAME:"mastercrafted_hoe_head-schematic",NAMESPACE:"forgero",STATE_TYPE:"STATE"},{ID:"minecraft:mangrove",NAME:"mangrove",NAMESPACE:"minecraft",STATE_TYPE:"STATE"}],NAME:"mangrove-mastercrafted_hoe_head",NAMESPACE:"forgero",STATE_TYPE:"COMPOSITE",TYPE:"HOE_HEAD",UPGRADES:[]}}"

id: "refined_pickaxe_head-schematic"
nbt: {FORGERO:{CONDITIONS:["forgero:sturdy"],ID:"forgero:refined_pickaxe_head-schematic",NAME:"refined_pickaxe_head-schematic",NAMESPACE:"forgero",STATE_TYPE:"STATE"}}

id: "jungle-lightweight_pickaxe_head"
nbt: "{FORGERO:{COMPOSITE_TYPE:"SCHEMATIC_PART",CONDITIONS:["forgero:swift","forgero:light"],ID:"forgero:jungle-lightweight_pickaxe_head",INGREDIENTS:[{ID:"forgero:lightweight_pickaxe_head-schematic",NAME:"lightweight_pickaxe_head-schematic",NAMESPACE:"forgero",STATE_TYPE:"STATE"},{ID:"minecraft:jungle",NAME:"jungle",NAMESPACE:"minecraft",STATE_TYPE:"STATE"}],NAME:"jungle-lightweight_pickaxe_head",NAMESPACE:"forgero",STATE_TYPE:"COMPOSITE",TYPE:"PICKAXE_HEAD",UPGRADES:[]}}"

id: "gold-path_digger_shovel_head"
nbt: "{FORGERO:{COMPOSITE_TYPE:"SCHEMATIC_PART",CONDITIONS:["forgero:durable","forgero:mighty"],ID:"forgero:gold-path_digger_shovel_head",INGREDIENTS:[{ID:"forgero:path_digger_shovel_head-schematic",NAME:"path_digger_shovel_head-schematic",NAMESPACE:"forgero",STATE_TYPE:"STATE"},{ID:"minecraft:gold",NAME:"gold",NAMESPACE:"minecraft",STATE_TYPE:"STATE"}],NAME:"gold-path_digger_shovel_head",NAMESPACE:"forgero",STATE_TYPE:"COMPOSITE",TYPE:"SHOVEL_HEAD",UPGRADES:[]}}"
