### ISSUE TITLE
Add config option for deleting recipes

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#457]
Addons might want to delete recipes from the game to make it easier to integrate Forgero into the progression. Create a config option that allows you to list recipe identifiers that will be deleted from the game.

**Comment by Steveplays28** [comment]
Might be worth putting up a wiki page that shows how to make a datapack/Forgero extension pack to do this instead?
Much easier than making a new system to handle a use case that can already be covered by datapacks/Forgero extension packs.

**Comment by SigmundGranaas** [comment]
That is true. I was thinking this would require less work for people integrating Forgero into their stuff. I already am using the system for deleting recipes from the recipemanager, but this isn't exposed to users.

I guess for now it is better to explain how to do it the vanila way in the wiki so there's less features to maintain.
