### ISSUE TITLE
Gem placement/texture feedback 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#461]
### **placement**

![image](https://user-images.githubusercontent.com/115664543/219877391-5f3b71ae-2f36-4937-8fde-28e0e8cfc374.png)

So first looking at the placement I think a couple are spot on. The gems in the swordguards look cool and make sense. Those should stay. Only the duelling guard is bugged? It doesnt even show the gem (probably wrong order on the textures). The gems on the actual tool parts dont make alot of sense to me. I think the gems should be only available for bindings and guards. Why? It makes the most sense, looks the best and is probably easier to balance then having 10 different toolparts all capable of holding gems. 

![image](https://user-images.githubusercontent.com/115664543/219877844-a704ec25-3d56-4b48-a1e8-eebf4c3319fc.png)![image](https://user-images.githubusercontent.com/115664543/219877912-4706b1c3-1fd0-4e53-8d73-e458b3accb78.png)![image](https://user-images.githubusercontent.com/115664543/219877925-98dbbcd4-d75a-4103-aecb-4cc7f291b181.png)![image](https://user-images.githubusercontent.com/115664543/219877953-9f2a3f1a-e64f-4c90-9552-26993e5f8c3b.png)![image](https://user-images.githubusercontent.com/115664543/219878021-8bcfb927-137e-4f61-9bf5-4ace05bd4592.png)![image](https://user-images.githubusercontent.com/115664543/219878039-04546436-28e4-4c60-a236-9078a7411283.png)![image](https://user-images.githubusercontent.com/115664543/219878094-7e5e9b04-7ab9-410a-9858-d34f7fb913b2.png)

As you can see in the image the gem in the binding looks good on most parts, in the axes it should be put one pixel down so its centered. 

### **texture**

The texture right now is just too small. I think, this is debatable tho. I made an example to make it look a bit bigger. Was a quick tryout so will need improving further if actually used. 

![2023-02-18_18 10 08](https://user-images.githubusercontent.com/115664543/219878981-01991ac2-1a96-4860-b4ad-0ccb7b261ebf.png)

Here its as round as it gets in minecraft and a bit bigger. Giving it a bit of a better look? 

Maybe sparking/enchanted effect is also a cool addition, as they are basically the enchanting side of the mod. So giving it a good visual distinction is a good idea.

**Comment by SigmundGranaas** [comment]
I agree with the conclusion that gems should only be placed on bindings and sword guards. I never actually managed to integrate them properly into the tool heads.

When it comes to textures, I think we should try to keep them 16x16, I have had a lot of comments about the fact that the gems textures are looking different than other parts. It's probably going to look a bit boring, but if we pair it with extra particle/sparkling effects, I think it can be quite nice. Adding particles is fairly easy, and it would be cool to add unique effects for every gem.

**Comment by JorisDeBeer** [comment]
The current texture is 16x16 right?

**Comment by SigmundGranaas** [comment]
The current gem textures are 32x32, that's why they're slightly off, and looks kinda misplaced in my opinion
