### ISSUE TITLE
[Compat] With Simply swords

### ISSUE THREAD

**Issue by DanMeadWasTaken** [SigmundGranaas/forgero#462]
I'm curious how likely it'd be to have compat with mods like [Simply Swords](https://github.com/Sweenus/SimplySwords)? (by extension also [Better combat](https://github.com/ZsoltMolnarrr/BetterCombat))

It'd be really cool to be able to make the custom weapons from simply swords with mixed materials/traits. They already have compat with alot of popular mods including [gobber](https://www.curseforge.com/minecraft/mc-mods/gobber-fabric?page=4) (and soon to have compat with [Advanced netherite](https://www.curseforge.com/minecraft/mc-mods/advanced-netherite) through an addon although currently only available for their forge version).

**Comment by Steveplays28** [comment]
Better Combat should already be supported in the next update (`0.10.7`)!

**Comment by SigmundGranaas** [comment]
It would be possible to create an extension pack to support Simply sword, but it would require making all of their tools from the ground up using the forgero system. This would have to be done by the mod creators, or someone with explicit permission to use their assets to create the extensions. I would be down to support it, but there are currently some limitations of Forgero's part that does not make it possible to create items that would extend outside of the  frame without looking silly.

Looking to get this fixed when tackling bow, as I'll have to add a separation for different model states.

**Comment by DanMeadWasTaken** [comment]
Hmmm, alright, so in the future it should be possible to make a addon/extension to basically replicate the simply swords weapons but in the forgero system?

**Comment by SigmundGranaas** [comment]
That should be possible, but it would be best to work directly with the Simply swords authors to use their assets.

**Comment by DanMeadWasTaken** [comment]
Yeah, that's why I mentioned it to them as well- As I'm looking to help them out with support for expert tools and weapons- as from what I can tell, they mainly need someone to do the textures- as there would be A LOT of textures.

**Comment by Steveplays28** [comment]
Compat with Simply Swords would be neat, since I'm currently running both Forgero and Simply Swords on my custom modpack.
Expert Tools and Weapons is cool too, though a lot of work as you said.

**Comment by DanMeadWasTaken** [comment]
So the owner of simply swords has a [question ](https://github.com/Sweenus/SimplySwords/issues/37#issuecomment-1436155255)!

>Do you happen to know if Forgero requires textures to be made for each of these individual weapon parts (like the Expert Weapons mod), or is it using some kind of texture stitching code to achieve this?
I can't tell from a glance at thier CF and Github page.

>If it's the latter that will make it much easier to add compat for.

**Comment by SigmundGranaas** [comment]
Just wanna give a small update on this issue now. I had some time to play around with some of the stuff that is required for this compatibility to work.

I created a branch to work on some of the basic parts to get that working first.

### Texture scaling and display overrides
I managed to get dynamic resolution scaling to work, which means that normal 16x16 textures can be scaled down to fit 32x32 textures dynamically, so everything that is needed is to apply manual texture offsets to parts that need to be shifted to be in the correct place.

Display overrides also works, so the custom display model attributes of simply swords tools can also be used.

Here's some pictures of this working:

![image2](https://github.com/SigmundGranaas/forgero/assets/46557903/ff3b353f-d9a4-4cdd-8b7b-5a32a00870b5)

![image1](https://github.com/SigmundGranaas/forgero/assets/46557903/4d110834-2a76-486d-99d9-560ad099a8a6)

### Animated texture layers
I am currently working on implementing a system for adding custom texture layer elements, which will make it possible to recreate lots of the elemental effects on some of the swords. This will be tracked in this branch: #623 

[Screencast from 2023-05-29 22-32-36.webm](https://github.com/SigmundGranaas/forgero/assets/46557903/21f90f8d-0f60-4eb4-80e0-825a7db6f083)

Stuff that still needs work:
- [x] #622 
- [x] Integrated support for the custom feature/properties of the weapons
- [x] Support for combining the tooltips of both mods
- [ ] Actually implement all of the different weapons

When The code required to complete this compat is done, I will likely ask from support in the community to actually create and fine tune all of the schematics, textures, parts and models. Creating compatability for the basic tool variants should be fully supported now.

**Comment by JorisDeBeer** [comment]
#211
