### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#475]
No clue how to label this. Code quality?

**Comment by Steveplays28** [comment]
I'll check which branches can be removed in a bit.

**Comment by Steveplays28** [comment]
Almost done, just a few more things that need discussing.

**Comment by SigmundGranaas** [comment]
I deleted a few branches as well as the protected one.

**Comment by Steveplays28** [comment]
Alright thanks, this is looking much cleaner and more manageable.
