### ISSUE TITLE
[Crash] Multi Mod Conflict?

### ISSUE THREAD

**Issue by greensad** [SigmundGranaas/forgero#479]
I'll be totally honest I'm not sure what's going on here but I'm getting a crash with a multitude of mods when enabled in tandem. Removing any one of the following mods seems to fix the crash (some are dependencies however). I'm not really sure where to submit this but Forgero was the first conflict I identified so it's your lucky day I guess.

Minecraft 1.19.2
Quilt 18.2

[BCLib 2.1.6](https://modrinth.com/mod/bclib)
[Bedrockify 1.5](https://modrinth.com/mod/bedrockify)
[Bedspreads 6.0.0](https://modrinth.com/mod/bedspreads)
[Better Nether 7.1.3](https://modrinth.com/mod/betternether)
[Better Taskbar 1.5.1](https://modrinth.com/mod/better-taskbar)
[Bookshelf 16.2.17](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Botania 437](https://modrinth.com/mod/botania)
[CorgiLib 1.0.0.22](https://modrinth.com/mod/corgilib)
[EMI 0.6.5](https://modrinth.com/mod/emi)
[Enchant the Rainbow 1.1.0](https://modrinth.com/mod/enchant-the-rainbow)
[Enchanting Infuser 4.2.2](https://modrinth.com/mod/enchanting-infuser)
[Enhanced Celestials 2.1.0.5](https://modrinth.com/mod/enhanced-celestials)
[Entity Texture Features 4.3.1](https://modrinth.com/mod/entitytexturefeatures)
[Forge Config API Port 4.2.11](https://modrinth.com/mod/forge-config-api-port)
[Forgero for Fabric 0.10.6](https://modrinth.com/mod/forgero)
[Patchouli 77](https://modrinth.com/mod/patchouli)
[Puzzles Lib 4.3.12](https://modrinth.com/mod/puzzles-lib)
[Quilted Fabric API 4.0.0 beta 28 & QSL 3.0.0 beta 29](https://modrinth.com/mod/qsl/versions)
[Starlight 1.1.1](https://modrinth.com/mod/starlight)
[Trinkets 3.4.2](https://modrinth.com/mod/trinkets)

**Log:** https://pastebin.com/h3cnFPDj

**Prism Launcher Instance:** https://drive.google.com/file/d/1COmoenH9bkAUhim_UHm5wCupqM-hT1NP/view?usp=share_link

**Comment by SigmundGranaas** [comment]
So it seems like mixins are failing for Botania  in a worldrenerer class. I do believe I also have a mixin there's so It's possible our mods are conflicting on the mixin injection. I think this can be fixed easily, but I'll have to have another look at it when I have some more time.

Also, not familiar with how quilt handles things, but hopefully that's not the source of the error. Thanks for the report!

**Comment by greensad** [comment]
ahhh yw, okay, I'll post on the botania issue tracker too

**Comment by SigmundGranaas** [comment]
Alright, I had another look at this issue, and I can't really find any connection to Forgero.

The crash comes from this mixin:
```
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Variable modifier target for net/minecraft/class_761::makeMoonBigger was removed by another injector [INJECT Applicator Phase -> #botania:botania_xplat.mixins.json:client.LevelRendererMixin from mod botania -> Apply Injections ->  -> Inject -> #botania:botania_xplat.mixins.json:client.LevelRendererMixin from mod botania->@ModifyVariable::makeMoonBigger(Lnet/minecraft/class_1159;)Lnet/minecraft/class_1159;]
```

So the issues likely stems from mods that inject something into the same function as botania does to make the moon bigger. I tried recreating your setup of mods, but I could not recreate the crash so I can't really do any more from my end.

**Comment by supermike1999** [comment]
It appears Enhanced Celestials 2.1.0.5 causes this issue as I got the same Crash error when attempting to load these mods together

**Comment by SigmundGranaas** [comment]
I'll check that version to see if I can reproduce the issue!
