### ISSUE TITLE
1.19.2 client crash

### ISSUE THREAD

**Issue by netcore10** [SigmundGranaas/forgero#488]
https://mclo.gs/Ngth0a7

1.19.2 ... quilt 18.2

**Comment by Steveplays28** [comment]
Duplicate of #432. Issue should be fixed with the release of the next `0.10.7` release candidate.

**Comment by SigmundGranaas** [comment]
This issue was fixed by #480 
This crash will be fixed by the upcoming 0.10.7

**Comment by SigmundGranaas** [comment]
Also, I would like to take this opportunity to mark my answer as a duplicate of Steve's.

**Comment by netcore10** [comment]
Apologies, i didn't know.

**Comment by Steveplays28** [comment]
No worries!
