### ISSUE TITLE
Forgero 0.10.8

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#499]
Todo:
- [x] #473 
- [x] #495 
- [x] #500
- [x] #482 
- [x] #496 
- [x] #464 
- [x] #502 
- [x] #505 
- [ ] Something Joris forgot, which is forever lost to the times
- [x] Replace reinforced handle with refined
- [x] Add missing texture file
- [x] Add translation for vein mining dirt
- [x] #523
- [x] #375 
- [x] #344

**Comment by JorisDeBeer** [comment]
Cherrypicking png file :)

**Comment by JorisDeBeer** [comment]
Remove reinforced handle and put it in as upgrade?

**Comment by SigmundGranaas** [comment]
Yeah I think that's a good idea

**Comment by JorisDeBeer** [comment]
PAGE FOR FEATURES
