### ISSUE TITLE
cannot join my server due to mismatched mods, everythings the same, but it claims to not find it on the server.

### ISSUE THREAD

**Issue by netcore10** [SigmundGranaas/forgero#511]
https://paste.atlauncher.com/view/dbe40007-e95a-41d7-af96-b7b23871dbe2

1.19.2

**Comment by netcore10** [comment]
I'll be doing a complete fresh install just to be sure later, but it seems to mention forgero tags

**Comment by Steveplays28** [comment]
Hey, thanks for the report!
Could you please check if the issue still occurs if only Forgero is installed?

If that works but your modpack still doesn't, I recommend to do a [binary search of your mods](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a), as well as updating Quilt and QSL/QFAPI.

**Comment by SigmundGranaas** [comment]
Hello! The reported tags have been fixed by #496, and will be published with Forgero 0.10.8. But this is unrelated to the issue with mismatched mods. I ran into the mismatched mod issue recently, both with and without the tags warnings. I don't know what causes that issue exactly, but I had to switch back to Fabric for it to work as expected.

I believe what caused the issue for me was running a Fabric server, and trying to connect with a Quilt client, but I don't know if that is the case for you.

**Comment by netcore10** [comment]
our server and client is both quilt

**Comment by netcore10** [comment]
so far i have begun redoing the server, but we ran into an unrelated issue that we need to fix first.

**Comment by netcore10** [comment]
> so far i have begun redoing the server, but we ran into an unrelated issue that we need to fix first.

Once that's done i can see if we can still join or weather the mods become mismatched. I did notice modrinth doesn't force you to get the arrp mod client side, which could've been the issue - this might take a while as i'm one person, so apologies if it's left up for quite a bit as i power through problems.

**Comment by SigmundGranaas** [comment]
I believe ARRP is shipped alongside Forgero. Take your time, it would be nice to figure out a solution if Forgero is causing this issue, and thanks for taking the the time to test and debug Forgero in modded environments!

**Comment by SigmundGranaas** [comment]
To clarify, ARRP *should* be shipped with Forgero, so if it isn't, that's an issue I need to fix as well.

**Comment by Steveplays28** [comment]
> this might take a while as i'm one person, so apologies if it's left up for quite a bit as i power through problems.

No worries!

**Comment by SigmundGranaas** [comment]
I'll close this issue for now, feel free to open it again if this issue persists
