### ISSUE TITLE
Silver textures seem to be broken.

### ISSUE THREAD

**Issue by ambientNexus** [SigmundGranaas/forgero#519]
![image](https://user-images.githubusercontent.com/53546918/224513320-e09a239b-1ba4-455a-bce6-33891326e9ca.png)
When installed alongside the Mythic Metals mod, silver seems to be showing a missing texture, while all other metals show their corresponding textures properly.

**Comment by SigmundGranaas** [comment]
Hey, thanks for the issue! Which MC and forgero versions are you using?

**Comment by SigmundGranaas** [comment]
It seems silver was removed by mistake, it's back now
