### ISSUE TITLE
Balancing feedback

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#524]
- [x] Oak sword attack damage is 5 -> base game is 4 (the wood parent should be toned down one) 
- [x] Guard schematic speed switched around base game has 1.6 forgero has 1.15.
- [x] Jungle planks have +-0.1 attack speed?
- [x] Some woods add raw durability when upgraded in utility -> should be with all woods but only values should be different. 
- [x] stone pickaxe has 4.6 attack damage base game only 3. 
- [x] Fix the weird rarity values -> keeping them 10, 15, 20 makes sense and is logical. No reason to add 1 and 2's. 
- [x] HOE SCHEMATIC WEIGHT IS MILLIONS OFF base game has 4 forgero has 1
- [x] gold should be looked at again. tools are very different. 
- [x] Maybe good idea to streamline tooltip and remove all .0 values? 
- [x] soft materials dont add weight -> on purpose or?

**Comment by SigmundGranaas** [comment]
Soft material not adding weight was sortof done on purpose. Some of the weight values for heavier materials goes really low, so I didn't wanna add any extra cost of using soft materials. as they are generally considered inferior.
