### ISSUE TITLE
Create a new building to showcase different tools and weapons that can be made

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#535]

**Comment by JorisDeBeer** [comment]
Should it be a pretty building or just big wall much to see?

**Comment by SigmundGranaas** [comment]
Preferably pretty. I think it would be a good idea to find a really cool looking armory or similar medieval building and base our design on that. There are so many cool building examples out there

**Comment by JorisDeBeer** [comment]
We talked about this, I doubt this is something we should still do. A good made modonomicon book works better than a building no?
