### ISSUE TITLE
Gems on fabric can't be utilized (0.10.7 BETA)

### ISSUE THREAD

**Issue by AverageCodeEnjoyer2004** [SigmundGranaas/forgero#537]
Can I ask if there is a way to use gems to enhance tools in this version for fabric yet and I just can't find it? Thanks in advanced :)

**Comment by SigmundGranaas** [comment]
Hey! Gems are absolutely suppose to be able to enhance tools, but we've had some reports of a bug that's preventing gems from being applied, so we're looking into it for a fix!

**Comment by LunaFolf** [comment]
We've noticed on our server that gems can currently only be applied to mastercrafted and refined parts, which is a bit problematic with the fact you can currently only get the normal version of schematics for these parts.

Our temporary solution has been to add some override recipes in our own datapack, to add in mastercrafted schematic recipes - so that we can apply gems to these components.

**Comment by SigmundGranaas** [comment]
Schematics are available, but only found as loot. I can see why some player might want to be able to craft it from existing parts. We'll have to take this into consideration when reworking/implementing some of the progression based mechanics in the mod.

**Comment by LunaFolf** [comment]
> Schematics are available, but only found as loot.
Interesting, what's the drop rate like? I understand keeping it as loot only given they are meant to be more advanced and higher quality.

My server has deep mob learning, and I was simulating the loot drops for pillagers for a LONG time, I have chests filled to the brim with different schematics and different parts, but I never once got a mastercrafted pickaxe head...

**Comment by SigmundGranaas** [comment]
Oh, the mastercrafted loot is only available from loot chests. This should probably be included in the docs somewhere to make it less confusing.

Mobs drop some stuff, but mostly basic variants.

**Comment by SigmundGranaas** [comment]
Also, the loot injection system is migrated to a datapack format which makes it possible to add Forgero loot entries to all existing loot tables.

**Comment by SigmundGranaas** [comment]
@AverageCodeEnjoyer2004 have you tested to most current 0.10.8 release of Forgero? I have tried to reproduce the issue with gems not being applicable to parts, but I haven't been able to reproduce the issue. Are you applying the gems to bindings in the smithing table?

**Comment by SigmundGranaas** [comment]
Also, I bundle Forgero with Arrp, so if that is installed separately, it might cause issues. This is something I have to look into further.
