### ISSUE TITLE
Binding reinforcement doesnt work properly

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#539]
Title 

![image](https://user-images.githubusercontent.com/115664543/226647803-b0b1dd24-123a-4624-9b5b-e874618d53fe.png)

While reinforcement texture is -> 

![image](https://user-images.githubusercontent.com/115664543/226647872-8b70793c-de87-4928-a77b-3ca6d8790387.png)

**Comment by SigmundGranaas** [comment]
Alright, it seems like my update also broke some stuff >:(

**Comment by SigmundGranaas** [comment]
Fixed :+1:
