### ISSUE TITLE
Make overrides possible in compat files instead of vanilla ones 

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#542]
-

**Comment by JorisDeBeer** [comment]
This is already done right?

**Comment by SigmundGranaas** [comment]
I am not sure actually, I have to verify

**Comment by JorisDeBeer** [comment]
I mean you made the mixin model files for betternether that are placed in the compat directory

**Comment by SigmundGranaas** [comment]
There might have been one small issue that I wanted to fix with this. I can't remember so I have to double check that it works as intended

**Comment by SigmundGranaas** [comment]
I think this works sufficiently.
