### ISSUE TITLE
Conditions do not appear to apply to parts made from schematics and vice versa

### ISSUE THREAD

**Issue by UnusedCactus** [SigmundGranaas/forgero#543]
When attempting to make a part from the necessary materials and a schematic with conditions, the conditions do not appear to be applied to the resulting item.
![image](https://user-images.githubusercontent.com/87100678/227790122-a0a1e1c5-bbfe-4b8c-89bd-547003f2b76e.png)
![image](https://user-images.githubusercontent.com/87100678/227790239-44802373-1a0d-4c89-ba23-a2082271772a.png)
This also applies to schematics made from parts, either made using the assembly station, or crafting by hand. This may be a feature, so ignore this if it is.
![image](https://user-images.githubusercontent.com/87100678/227790358-26558d69-bfb2-42b4-bc2f-4ecc4f228e78.png)
![image](https://user-images.githubusercontent.com/87100678/227790382-70fa9564-9a37-46ec-b055-53db74dbabd9.png)
(^the resulting schematic)
![image](https://user-images.githubusercontent.com/87100678/227790422-0e823e6f-6ede-40e5-b708-8f88046422f1.png)
![image](https://user-images.githubusercontent.com/87100678/227790454-f8c5c507-3e2f-45ba-93d4-76050ee455a8.png)
This isn't like the issue where the REI crafting recipe menu shows the incorrect result (that might not be able to be fixed... not a deal breaker anyways), as it occurs without fail in regular crafting tables and the assembly station.

**Comment by SigmundGranaas** [comment]
Hey! Thanks for the issue, I should probably make it a bit more clear exactly how conditions apply. Don't worry, I haven't really made this clear anywhere so it's quite natural to assume this is an issue.

Conditions are not supposed to be able to carry over when going from part -> schematic. The process for creating schematics is also going to undergo a rework at some point in the nearish future, so the implementation is currently quite simple.

The attributes of the condition will carry over when used to craft parts. If you compare the lightweight pickaxe head you created with one crafted with another schematic, you should see the that the attributes are actually different. The condition names stay on the part that they originated from. If this is not the case, and they have the exact same stats, even though one was created from a schematic with conditions, then it is bugged. So it would be nice of you could double check that :+1:

**Comment by UnusedCactus** [comment]
![image](https://user-images.githubusercontent.com/87100678/227796497-e5f48448-c1ad-437e-97cb-8ff94c799aa9.png)
![image](https://user-images.githubusercontent.com/87100678/227796515-725f68ce-21eb-4951-a40e-00942310ba4e.png)
![image](https://user-images.githubusercontent.com/87100678/227796525-c2003b90-518f-4bde-8a6f-62d50ca2277b.png)
The stats do change, however the change is not really obvious. Using 3 different Lightweight Pickaxe Head schematics (the last one is normal) there is definitely a change in stats. I just couldn't really tell I guess.

**Comment by SigmundGranaas** [comment]
That's a good point. The mod has some issues with displaying how stats differ when upgraded. There have been a suggestion to colorize the attributes based on how they compare to the default one. Do you think this would make it easier to see that the part has indeed been affected by the condition of the schematic?

**Comment by SigmundGranaas** [comment]
An example of this would be that the stat that has changed would turn more green if it's better and more red if it's getting worse.

**Comment by SigmundGranaas** [comment]
In hindsight, it would make a lot more sense if the names of the conditions also applied to the parts that was crafted with a conditioned schematic.
