### ISSUE TITLE
Look into odd behaviour of vein mining.

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#551]
Reduce initial vein mining depth
Look into reports of instamine
Look into alternate algorithms for vein mining trees.

**Comment by BryceBubbles** [comment]
Hi, I'm Just adding to the reports of being able to instamine with ore mining pickaxe heads - tried oak, iron, diamond.
I'm using forgero-fabric-0.10.9+1.19.2

**Comment by JorisDeBeer** [comment]
Fixed
