### ISSUE TITLE
Crash (Fabric): Crash on initialize caused by compat with Tool Stats.

### ISSUE THREAD

**Issue by Golemosus** [SigmundGranaas/forgero#558]
Minecraft 1.19.2
Fabric modloader
Mods:
Forgero 0.10.8
Tool Stats. 12.0.2
Fabric API 0.76.0
Bookshelf 16.2.18

Issue only occurs with Tool Stats present.

Crash log:
[crash-2023-04-06_17.04.57-client.txt](https://github.com/SigmundGranaas/forgero/files/11171985/crash-2023-04-06_17.04.57-client.txt)

**Comment by SigmundGranaas** [comment]
Thanks for the issue! This is most likely due to a dirty mixin to toolstats to make it do some stuff that I don't even remember anymore. I'll remove the mixin which should solve this issue.

**Comment by SigmundGranaas** [comment]
It seems like this issue has already been patched, and will be updated in 0.10.9
