### ISSUE TITLE
Mending enchantment doesn't work on diamond pickaxes

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#559]
![screenshot of a diamond Forgero pickaxe with mending and efficiency 4](https://media.discordapp.net/attachments/981828977813504021/1093931714717417512/image.png)

**Comment by SigmundGranaas** [comment]
I tried recreating this issue but it worked perfectly fine for me? Could you test if this only happens for this tool, cause in my testing, basic tools worked with mending.

**Comment by Steveplays28** [comment]
Alright, will test later!

**Comment by SigmundGranaas** [comment]
I am closing this as stale unless you have some more info in this.

**Comment by Steveplays28** [comment]
I'll take a look at some point, forgot about this issue. Last time I checked that pickaxe had the same issue still, so it's not a one off situation.

**Comment by SigmundGranaas** [comment]
Aight, just repoen the issue of you find something!
