### ISSUE TITLE
Items Getting an Empty NBT Tag Appended to Them

### ISSUE THREAD

**Issue by TomVHS** [SigmundGranaas/forgero#560]
When blocks are broken while holding that same block in your hand, an empty NBT tag is appended to it.
Confirmed by using an NBT editor/viewer.

Steps to reproduce:
- Install fabric + forgero (latest at time of reporting bug, 0.10.8)
- Create a new world
- Get blocks that can be broken by hand (dirt, sand, torches, etc.)
- Place some blocks down
- While you still have those blocks in your hand, break the one(s) you have placed down

Here is a video showing the bug (uploaded to YouTube as file size was >10MB):
https://youtu.be/zuHXK6xbxXI?t=8

**Comment by SigmundGranaas** [comment]
Wow, that is a really wierd issue, but thanks for reporting it! I haven't a clue as to what is causing this issue, as it is far from intended, but I'll look into it. This might also have side effects that are far worse. 

Might I ask how you encountered this issue? It seems very odd

**Comment by Steveplays28** [comment]
I believe I've had this issue as well on my server, can confirm
