### ISSUE TITLE
Schematic Recipe Conflicts

### ISSUE THREAD

**Issue by GoldenFurredFox** [SigmundGranaas/forgero#583]
The basic tool head schematics conflict with every other tool head schematic, and it's hit or miss if you'll get the schematic for the tool head you're trying to craft or just a basic tool head. One example I can think of right off hand is that I have a Warped Grave Digger Head, but when I try to combine it with paper, it tries to craft a Shovel Head. Recipe conflict helpers like polymorph aren't updated past 1.19.2, and the modpack I'm playing on uses 1.19.3, so the only way it's going to be fixed is if you make it so that the only tool head that can be used used to make a basic tool head schematic is a basic tool head, instead of every tool head of that type.

**Comment by SigmundGranaas** [comment]
Hey! I can see how this can be a frustrating issue, but for now this is intended. Right now, there is no other way of obtaining advanced schematics except for finding them as loot. The paper + part = schematic recipes are intended to be an easy way to obtain base schematics.

We know this is a big issue, and are working on a way to fix this in an upcoming schematic update where we overhaul how to obtain different schematics.

**Comment by GoldenFurredFox** [comment]
As of right now, there are absolutely no craft-tweaker-like mods for 1.19.3. I've attempted to call the devs of both Polymorph and Craft-Tweaker to arms in their discord servers, but neither have responded, so I'm going to move on to creating GitHub issues instead.

**Comment by Steveplays28** [comment]
Datapacks are the better option in newer Minecraft versions, since, as you said, CraftTweaker-like mods haven't updated yet, and there's gonna be 0 mod compat until a while after they do update.

**Comment by SigmundGranaas** [comment]
Added an option to make it possible to craft all schematics by setting enableRecipesForAllSchematics = true

**Comment by CandyGumdrop** [comment]
Having `enableRecipesForAllSchematics` set to false, as it is by default, I'm finding I can still obtain the schematics by selecting a recipe variant in Polymorph.  Are purposefully conflicting recipes used as a means of disabling the other recipe?  If so, this seems unreliable, as mods which allow selecting between conflicting recipes to use are a common thing to have.

**Comment by SigmundGranaas** [comment]
This is not done on purpose, so this would be a bug. There might be overlap with recipes because of a recipe generator that hasn't been configured properly. Does this happen to all parts, or only select types of parts?

**Comment by CandyGumdrop** [comment]
I've tried with a few different types of tool part and it works for all of them.
