### ISSUE TITLE
ModMenu 6.2.0 and 6.2.1 crashes my game, seems to be incompatible with Forgero

### ISSUE THREAD

**Issue by ManicQuinn** [SigmundGranaas/forgero#584]
Here's the two crash reports, think they're for each version:

[crash-2023-04-21_06.03.56-server.txt](https://github.com/SigmundGranaas/forgero/files/11290793/crash-2023-04-21_06.03.56-server.txt)
[crash-2023-04-21_06.08.04-server.txt](https://github.com/SigmundGranaas/forgero/files/11290794/crash-2023-04-21_06.08.04-server.txt)

**Comment by Steveplays28** [comment]
Fixed by my linked PR. Will hopefully release soon:tm:
