### ISSUE TITLE
Assembly Station Dupes Resources

### ISSUE THREAD

**Issue by TheTennessee** [SigmundGranaas/forgero#591]
I have been on a server with some folks for a little while now, and never got into forgero until recently. I was told by a friend that zombies could drop netherite tool parts and those could be disassembled. So, what did I do? I sat at my zombie spawner and got one to test it. When I did, I noticed that I got a netherite ingot, but the tool part was still in the station. I picked it up, put it back down, and got another ingot. I got 4 of them and realized it was just duping it.

I'm using version 0.10.6 on 1.18.2, with fabric 0.14.14, and there's no further updates available to me on this version. If it has been fixed in 1.19, can I request that it be backported? This is pretty game breaking.

**Comment by Steveplays28** [comment]
Not sure if this is the same issue as what is fixed by #569, if it is it could probably be cherry picked and backported. @SigmundGranaas

**Comment by TheTennessee** [comment]
If I knew the steps to try it, I could find out if it still exists in that version as well.

**Comment by SigmundGranaas** [comment]
The assembly station has been simplified in the upcoming 0.10.9 update, which hopefully resolves all issues like this. It will no longer allow you to input anything in the grid, which will solve a lot of issues relating to if an item has been disassembled or not.

The goal is for 0.10.9 to be the last update to 0.10.x before moving on to 0.11. I would like to backport the update, but I have very little time right now, so it will be done when there is more time available

**Comment by SigmundGranaas** [comment]
> Not sure if this is the same issue as what is fixed by #569, if it is it could probably be cherry picked and backported. @SigmundGranaas 

Might resolve the issue, the biggest problem is that the 1.18.2 branch is still on the wrong project structure

**Comment by SigmundGranaas** [comment]
Also, zombies should not drop netherite parts so let me double check that.

**Comment by SigmundGranaas** [comment]
Forgero 0.10.9-rc1+1.18.2 is released now, so I believe this issue should be solved.
