### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by Rogenar** [SigmundGranaas/forgero#594]
Forgero [Fabric]: Version 0.10.8+1.19.3 crashes the game.
[latest.log](https://github.com/SigmundGranaas/forgero/files/11412127/latest.log)
[rei.log](https://github.com/SigmundGranaas/forgero/files/11412128/rei.log)
[rei-issues.log](https://github.com/SigmundGranaas/forgero/files/11412129/rei-issues.log)
[crash-2023-05-06_13.36.13-client.txt](https://github.com/SigmundGranaas/forgero/files/11412130/crash-2023-05-06_13.36.13-client.txt)

**Comment by SigmundGranaas** [comment]
This issue has been fixed by #545
I am patching a prerelease version for 1.19.3 as we speak, which should no longer have this problem

**Comment by Rogenar** [comment]
[latest.log](https://github.com/SigmundGranaas/forgero/files/11412249/latest.log)
[rei.log](https://github.com/SigmundGranaas/forgero/files/11412250/rei.log)
[rei-issues.log](https://g
[crash-2023-05-06_14.57.14-client.txt](https://github.com/SigmundGranaas/forgero/files/11412252/crash-2023-05-06_14.57.14-client.txt)
ithub.com/SigmundGranaas/forgero/files/11412251/rei-issues.log)
It causes crash in version 0.10.9.

**Comment by SigmundGranaas** [comment]
Alright, that changes it somewhat. Which language are you currently using in game?

**Comment by Rogenar** [comment]
Turkish

**Comment by SigmundGranaas** [comment]
Okay, the error seems to come from this: Non [a-z0-9/._-] character in path of location: forgero:items/trÄ±nket 

The appropriate id is: forgero:items/trinket

Do you have a mod or anything else on your system that can have changed this?

**Comment by Rogenar** [comment]
There are several mods that use the trinket mod.
Unfortunately there is no mod that can change it.

**Comment by SigmundGranaas** [comment]
Issue seems to come from how Turkish locale translation handle translating an uppercase I. I have changed the entire system to now use Locale.ENGLISH, which should properly handler all internal strings and identifiers. I believe this should fix the issue. Feel free to reopen this issue if the problem persists.
