### ISSUE TITLE
ModMenu crash on client in 1.19.4

### ISSUE THREAD

**Issue by Merith-TK** [SigmundGranaas/forgero#598]
Client Log
https://mclo.gs/4WBIT3v
Server Log
https://mclo.gs/8YIcSjG

Client Crashes and Modmenu appears to take the fall

**Comment by SigmundGranaas** [comment]
This is a dirty mixin issue which has been fixed. I posted a patched har on the discord if you can't wait for the 0.10.9 1.19.4 port later this week.

**Comment by SigmundGranaas** [comment]
For reference: https://discordapp.com/channels/981828752029925408/981828752659083266/1105495479552327700

**Comment by Steveplays28** [comment]
Duplicate of #584, fixed by #585

**Comment by SigmundGranaas** [comment]
New version is up now.
