### ISSUE TITLE
Forgero reference book missing entries

### ISSUE THREAD

**Issue by DailyEffortBird** [SigmundGranaas/forgero#599]
![image](https://github.com/SigmundGranaas/forgero/assets/122572140/86d2d390-e06d-477a-8431-1c1c61007760)
Hovering over Forgero items with the book in my inventory doesn't work either.
Using Forgero 0.10.9 for Minecraft 1.18.2.

**Comment by Steveplays28** [comment]
Hi, thanks for the report! Do you mind sending the log file that contains the error stack trace?

**Comment by DailyEffortBird** [comment]
[latest.log](https://github.com/SigmundGranaas/forgero/files/11445202/latest.log)
Is this what you're looking for?

**Comment by Steveplays28** [comment]
Yes, thanks!

**Comment by SigmundGranaas** [comment]
Mangrove does not exist in 1.18.2, so I removed the material entry. It seems like the guide references this missing material, which crashes the book. It should be as easy as changing the wood type of the entry to another wood, like oak.
