### ISSUE TITLE
Disassembly station item duplication

### ISSUE THREAD

**Issue by CandyGumdrop** [SigmundGranaas/forgero#603]
It still seems to be possible to duplicate items using the disassembly station (using Forgero 0.10.9-rc1+1.19.2).

After placing something into the left-hand slot in the disassembly station, and removing an item from the grid on the right, the item disappears from the left-hand slot.  However, if you then click the empty slot, everything reappears in the grid on the right and can be removed again, allowing for infinite duplication.

As an additional note to this, stacks of items in the left-hand slot behave oddly when removing items from the grid, as more than just one disappears from the stack on the left.

**Comment by SigmundGranaas** [comment]
Nice catch! I'll try to recreate it so I can fix these issues
