### ISSUE TITLE
Possible to use just tool heads for mining

### ISSUE THREAD

**Issue by CandyGumdrop** [SigmundGranaas/forgero#604]
Holding a pickaxe / axe / shovel head on its own, it's possible to use this for mining without assembling a full tool with a handle.  This gives infinite durability.

**Comment by SigmundGranaas** [comment]
It seems I have forgotten to check if the item which carries the properties is an actual tool. Does the parts have differing mining speeds, or is there only the fact that it can be used to mine?

**Comment by CandyGumdrop** [comment]
The mining speed + mining level seems to match the type of tool head.

**Comment by SigmundGranaas** [comment]
Alright, then I know what is wrong, it should be an easy fix.

**Comment by Steveplays28** [comment]
LMAO
