### ISSUE TITLE
[1.19.2-0.10.9] Game crashes on world loading

### ISSUE THREAD

**Issue by Kiryonn** [SigmundGranaas/forgero#609]
I can't even make sense of what happens by looking at the logs. So instead i'll just give me my modpack and hope you can do something about it.
[1.19.2 - Fabric tech combat.zip](https://github.com/SigmundGranaas/forgero/files/11469650/1.19.2.-.Fabric.tech.combat.zip)
A piece of information that can help (maybe), is that when i disabled forgero and logged into the world, i had a patchouli book for forgero (that i obviously couldn't open since i disabled the mod)

**Comment by SigmundGranaas** [comment]
I need the log to be able to see what is going on.

**Comment by Kiryonn** [comment]
here you go [2023-05-13-1.log](https://github.com/SigmundGranaas/forgero/files/11469769/2023-05-13-1.log)

**Comment by SigmundGranaas** [comment]
It seems like EMI has an issue parsing the loot table:
`	at fzzyhmstrs.emi_loot.client.AbstractTextKeyParsingClientLootTable.fromBuf(AbstractTextKeyParsingClientLootTable.java:182) ~[emi_loot-0.6.2+1.19.jar:?]
	at fzzyhmstrs.emi_loot.client.ClientLootTables.lambda$registerClient$3(ClientLootTables.java:39) ~[emi_loot-0.6.2+1.19.jar:?]`
Have you tried without EMI?

**Comment by Kiryonn** [comment]
i haven't yet. and i think it's not EMI but it's addon "EMI Loot" by looking at the file name. making some tests right now

**Comment by Kiryonn** [comment]
### Without `EMI Loot`
it works

With REI variants (Roughly Enough Loot Tables)
seems to work when i replaced EMI mods with REI variants (why ? cause i was wondering if other loot mods would crash)

**Comment by SigmundGranaas** [comment]
I had a similar issue before with emi loot where it crashed if the loot table was to big. The solution was for me to reduce the size of the loot table, but that isn't really a fix, as this sounds more like an internal issue with emi loot and large loot tables.
