### ISSUE TITLE
Hi! my game crashed on startup, here is the log: https://gist.github.com/stunlocked1/6adb423156492de31d618e615f1dd097

### ISSUE THREAD

**Issue by inikishev** [SigmundGranaas/forgero#639]
Hi! my game crashed on startup, here is the log: https://gist.github.com/stunlocked1/6adb423156492de31d618e615f1dd097

**Comment by SigmundGranaas** [comment]
Thanks for the issue! It looks like one of the resource file has an improperly defined value, and the default value was not applied. It should be an easy fix, but it might be a while untill I'll be able to fix it unfortunately
