### ISSUE TITLE
Invisible items/advancements - slight incompatibility

### ISSUE THREAD

**Issue by mousekebab** [SigmundGranaas/forgero#659]
Using mod **Eating Animation** items from Forgero are **invisible** in **Inventory** and **Advancements**. In hand items visibility unaffected. [Fabric] 1.18.2

**Comment by SigmundGranaas** [comment]
Thanks for the issue!
I have seen another report about this incompatibility before, but never got around to looking to deep into it. My main theory is that both of the mods mixin to the same field in the model class to use their own models. I'll look into it when I have time :+1:

**Comment by SigmundGranaas** [comment]
This seems to have been fixed in eating animations 1.9.1 and above. I can't really do anything as their rendering mixin overrides my injection into the Itemrenderer. If that update does not get backported to 1.18.2, there's not a lot that can be done about this.
