### ISSUE TITLE
Tooltip should keep showing the extra stats it gets from updates.

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#676]
Currently after upgrading something the stats revert to normal (the green arrows vanish). I think we should keep this locked in at all times. So you can easily see that your pickaxe has more attack speed/durability then another pickaxe etc. It makes them feel special and is much clearer than right now. Also important when some upgrades arent visible or you are using the same material for a upgrade and a tool.

**Comment by Steveplays28** [comment]
Maybe integrate with [Equipment Compare](https://modrinth.com/mod/equipment-compare)?
