### ISSUE TITLE
Enchantments are lost when unbreakable tools are broken

### ISSUE THREAD

**Issue by Steveplays28** [SigmundGranaas/forgero#678]

**Comment by SigmundGranaas** [comment]
What, I thought this was fixed?

**Comment by Steveplays28** [comment]
I might've timing'd you, I can't test but feel free to close if it's fixed

**Comment by SigmundGranaas** [comment]
It was fixed by #672 . Clearing the nbt's caused the enchanmtents to disappear. I believe this is fixed, so we'll just repoen this if that was not the case

**Comment by Steveplays28** [comment]
Alright, thanks!
