### ISSUE TITLE
1.19.2 fabric - Totem not being removed from inventory when players die

### ISSUE THREAD

**Issue by Ureiah** [SigmundGranaas/forgero#685]
My players found an issue when forgero is on the server. They have a totem of undying in their offhand and die, the totem remains in the inventory. It only happens when forgero is enabled.

**Comment by SigmundGranaas** [comment]
Okay, it seems like the same issue as posted previously, but it seems I misunderstood what the issue was. I forgot to redirect the mixin if there's no totem applied to the Forgero tool. Should be an easy fix, so thanks for the heads up 👍
