### ISSUE TITLE
crash whenever i open the gui for the identity mod 

### ISSUE THREAD

**Issue by Taleuxss** [SigmundGranaas/forgero#706]
seems like this mod makes it crash when i open the idenity mod gui to select mob
i remove forgero and i can open gui without crash

**Comment by Steveplays28** [comment]
Hi Taleuxss, can you post your log file?

**Comment by Taleuxss** [comment]
understood https://mclo.gs/NSXAA5m

**Comment by Steveplays28** [comment]
Thanks! I'll look into it.

**Comment by JorisDeBeer** [comment]
Seems like a soul entity error? Should be fixed now its removed? Not sure tbh, keeping it open but we got no further reports of it so could also be a modconflict

**Comment by SigmundGranaas** [comment]
This should be fixed.
