### ISSUE TITLE
List for Features/Attributes

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#711]
We should also make a list of all of the different new features/attributes you think would be nice to have to create so that all new weapons/tools can have unique abilities/effects.

I know poison, bleeding and biome specific attributes are wanted, but if we have a longer list of attributes/features, it makes it easier for me to plan how to implement stuff in the long run.

_Originally posted by @SigmundGranaas in https://github.com/SigmundGranaas/forgero/issues/710#issuecomment-1712146503_
            

### New wanted for materials and tools:

- [x] Basically being able of inflicting all status effects like poison, bleeding etc. But when on tool the person themselves gets it like haste, bigger jumps etc. (this one is just a very big part of it)
- [x] Biome Specific
- [x] Dimension Specific
- [ ] Attack range 
- [x] Exploding on contact
- [x] Something bouncy for slime stuff? 
- [ ] THROWING TOOLS FOR LIGHTWEIGHT PACK AND SPEARS ETC?? also ground work for trident
- [x] Multitools

**Comment by SigmundGranaas** [comment]
Hehe, makes more sense to keep this as a separate issue.

**Comment by JorisDeBeer** [comment]
Yes, I will make the list soonTM

**Comment by JorisDeBeer** [comment]
### New wanted for materials and tools:

- [ ] Basically being able of inflicting all status effects like poison, bleeding etc. But when on tool the person themselves gets it like haste, bigger jumps etc. (this one is just a very big part of it)
- [ ] Biome Specific
- [ ] Dimension Specific
- [ ] Attack range 
- [ ] Exploding on contact
- [ ] Something bouncy for slime stuff?
