### ISSUE TITLE
Conditions getting overwritten when crafting

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#735]
Look into pommels with conditions having them removed when being inserted into a sword

**Comment by azul3ra** [comment]
I had this happen on a refined pickaxe head as well. The issue may not be unique to pommels.

**Comment by Fevix** [comment]
Had this happen with a binding I found. It was Quick and... something. 

Put it on a pick, suddenly it's just a regular binding.

**Comment by Fevix** [comment]
Further addendum: I found a sword blade schematic with Mighty on it, but the sword blades this schematic produces do not have Mighty.

**Comment by SigmundGranaas** [comment]
This has been fixed. Please reopen if the issue reappears
