### ISSUE TITLE
Look into wierd tooltip behavior on tools when holding modifier keys

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#745]
The tooltip should expand when holding the modifier, but it does not. This suggests that they cache key is not handled properly, so it's not choosing the correct tootip

**Comment by KitsuneNoMeiji** [comment]
(Minecraft version 1.20.1) I was having the same issue. After a test, I narrowed the cause down to Roughly Enough Items (REI) causing my issue. I'm not sure if this conflict was known, but after setting up a test instance with just this mod and REI, I was able to duplicate the issue of the modifier key not expanding the tooltip. Removing REI fixed it for me. Just Enough Items (JEI) works fine though.

**Comment by Fevix** [comment]
The pack I'm using uses EMI, not REI, and I have the same tooltip issues. Does the issue persist with Forgero and EMI? (at work, can't test myself)

**Comment by KitsuneNoMeiji** [comment]
It might be too late by now, but I can confirm that it works just fine with EMI.

**Comment by JorisDeBeer** [comment]
Closing this as stale
