### ISSUE TITLE
Tools vanishing when repairing

### ISSUE THREAD

**Issue by SigmundGranaas** [SigmundGranaas/forgero#752]
> I'm not entirely sure what to say about this, but it seems that only certain configurations will repair the tool, while the others will just return you the repair kit and void the tool. I've played in survival with the mod for quite a bit and it seems to be quite a persistent issue...

> I suppose I should mention that this was the latest version of Fabric 1.20.1, so maybe this is an 'old' version and the bug was fixed, but I thought I should mention it either way.

**Comment by JorisDeBeer** [comment]
Tried to reproduce so I repaired 64 broken pickaxes, no luck seems this is a conflict or fixed.
