### ISSUE TITLE
[Error] No data fixer registered for soul_entity

### ISSUE THREAD

**Issue by Kiryonn** [SigmundGranaas/forgero#759]
```
[04/11/2023 15:40:29 PM] [Render thread/ERROR] No data fixer registered for forgero:soul_entity
```
When loading Minecraft, i saw a redline in ATLauncher console. It doesn't prevent me from using the mod, i'm new to it so idk if it's an important feature or not. I don't know how it impact the gameplay either. I'll let you decide.
| | version |
|---|---|
| Minecraft | 1.20.2 |
| Loader | Fabric |
| Loader version | 0.14.24 |
| Forgero | 0.11.5 |

**Comment by SigmundGranaas** [comment]
This is a result of me being extremely lazy, sorry about that. It won't affect anything, but mc rightfully warns about entities not having a data fixer, as it can lead to troubles with serializing entities. This won't be a problem as the soul entity is currently not available in any version of the mod outside experimental use.

**Comment by SigmundGranaas** [comment]
But it causes an ugly error message, so I should get that fixed.

**Comment by Kiryonn** [comment]
That was a fast answer 👀. Thanks for the trouble.
