### ISSUE TITLE
[BUG] Upgrade Station and Disassembly blocks not breaking/lag

### ISSUE THREAD

**Issue by lostopkk** [SigmundGranaas/forgero#768]
https://github.com/SigmundGranaas/forgero/assets/50776714/5e59fb68-6ff2-4c46-8749-49b79e89b8d2

sorry for the lag

**Comment by SigmundGranaas** [comment]
Thanks for the issue! I am honestly unsure of what I should make of this. This seems to suggest that while the upgrade/disassembly station are present all other blocks are only breakable om the client side, which triggers the blocks to look broken but not actually be broken. 

Does this always happen, or just in this example? And do you know if this happens on single player as well? I have never encountered an issue like this before so I am not sure what would be causing it.

**Comment by lostopkk** [comment]
> Thanks for the issue! I am honestly unsure of what I should make of this. This seems to suggest that while the upgrade/disassembly station are present all other blocks are only breakable om the client side, which triggers the blocks to look broken but not actually be broken.
> 
> Does this always happen, or just in this example? And do you know if this happens on single player as well? I have never encountered an issue like this before so I am not sure what would be causing it.

I'm using a fabric server, I haven't tested singleplayer to work. yes it happens every time I put the 2 on

**Comment by JorisDeBeer** [comment]
Just tested this on a fabric server myself. Have zero issues, so closing this.
