### ISSUE TITLE
[Compat]: Gobber support

### ISSUE THREAD

**Issue by Nol-inuse** [SigmundGranaas/forgero#792]
gobber support ples pleples pleples pleples pleples pleples pleples pleples ple

**Comment by SigmundGranaas** [comment]
Gobber support have been considered for a long time. Support will probably be added when we have a solid plan for how to make each gem/material interesting. Can't give a timeframe, but it definitely makes sense to create an integration here.

**Comment by SigmundGranaas** [comment]
I just had a look at Gobber, but it seems that it never got updated past 1.19.2. Last commit was over a year ago, so I don't think this is going to happen. Feel free to reopen this issue if Gobber gets an update!
