### ISSUE TITLE
Crash with the Modernfix mod

### ISSUE THREAD

**Issue by seriousfreezing** [SigmundGranaas/forgero#799]
https://paste.atlauncher.com/view/a2b03141-8b03-40f8-a8e9-911ea43ea27d

**Comment by SigmundGranaas** [comment]
No idea what wen'tbwronf here but it definitely looks like an incompatibility. Does it crash instantly every time or does this happen occasionally?

It seems like we're both trying to load and manage dynamic models, which is causing probablems.

**Comment by seriousfreezing** [comment]
So every time I try to open your mod tab in creative mode, it causes Minecraft to stop responding and not come back for anything.

I checked and the error stops when you remove ModernFix or Forgero.

**Comment by SigmundGranaas** [comment]
Thanks! I'll try to look into where the mods are conflicting and see if it it's easy to disable dynamic rendering from modernfix's side

**Comment by SigmundGranaas** [comment]
mixin.perf.dynamic_resources=true

Setting this to false should fix the issue, but I'll also look into a specific option

**Comment by seriousfreezing** [comment]
Yes, it works normally without this option active. Thank you.
