### ISSUE TITLE
How to disable SoulEntity from config

### ISSUE THREAD

**Issue by Borailuce99** [SigmundGranaas/forgero#803]
Hi again. Yesterday I posted an issue about and incompatibility with Identity mod and forgero because of SoulEntity and I saw there was a new commit solving this problem but it seems to fail when building. I tried to clone the repository, edit the same file and build but it fails to build too.
Is there a way to disable only this entity to avoid the crash temporarily while is being solved? What happens if I set "useEntityAttributes" to false?

**Comment by Steveplays28** [comment]
Hi Borailuce, there's plans for modularizing this as Sigmund said (in the Discord server at least).
As for the build failing, the workflow shows up as failed since publishing to the Maven repository fails due to an outdated token, the build does succeed.
Check the PR, as the build was skipped in the 1.19 branch.

**Comment by Borailuce99** [comment]
I saw the code changed, but how can I apply that modification to my mod? Is a way to build and download the ".jar" mod file to install on server and client?

**Comment by SigmundGranaas** [comment]
You can either download the source code and build the mod yourself, or you can grab the latest snapshot from this link:
https://maven.sigmundgranaas.com/repository/snapshots/com/sigmundgranaas/forgero-fabric/0.11.7+1.19.2-4-g21f21a71-SNAPSHOT/

**Comment by SigmundGranaas** [comment]
There will be no option in the config for disabling the soul entity, it will have to wait to be put into a separate module. The entity attributes option only enables extra stats to be put into the vanilla tooltip location for attributes.

**Comment by Borailuce99** [comment]
Now the problem is that the issue is solved on 1.19 branch but I'm currently playing 1.20.1 so the snapshot is not working :(

**Comment by SigmundGranaas** [comment]
Then the fix will unfortunately have to wait until I update everything to 1.20. I'm currently working on some other features, so I probably won't do that until those are completed.

I don't expect that to take more than a week, but holidays might say otherwise.
