### ISSUE TITLE
New Recipe Tool_With_Binding does not function properly

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#817]
With the new recipe generator system one of the old ones, the tool_with_binding recipe does not generate the correct textures ingame. Mainly looking at the handle. 

I tried fixing this myself but I couldnt get anything that worked. 

Do you know a quick fix SIGG?

Or tbh we could also remove the recipe, to move players more to the upgrade station which makes sense?

**Comment by SigmundGranaas** [comment]
The problem seems to be that the binding is getting recognized as a part and it tries to construct a part from blade, binding and handle instead of crating a part from a blade + handle, and then upgrading it with a binding.
