### ISSUE TITLE
Negative durability on unbreakable tools

### ISSUE THREAD

**Issue by Gamerbolts** [SigmundGranaas/forgero#822]
Hello. I have your mod in my modpack. I was playing and testing and noticed when I use Ultamine from FTB with a Forgero tool it will go to negative durability and continue to work. Not sure if logs will help or not. I searched your github but did not see anything mentioned so thought I would post.

**Comment by JorisDeBeer** [comment]
Some logs & game version would be appreciated. 

We did have this issue in the past but I couldn't reproduce it with only forgero. Forgero also has his own vein mining tools for that part. Could be the code here is conflicting in some way.

**Comment by Gamerbolts** [comment]
I am on v0.11.11

This is a personalized large modpack. Here is my log
[latest.log](https://github.com/SigmundGranaas/forgero/files/13932167/latest.log)

**Comment by SigmundGranaas** [comment]
Does this happen every time, or just once in a while? I suspect that this is due to a mod conflict with another mod which does some generalized durability handling, which might throw off Forgero's own mixin for checking if the tool should break or not. I don't know half of the mods in the modpack so I cannot say which mod that would be, unfortunately, but we appreciate the issue either way!

**Comment by SigmundGranaas** [comment]
Could you paste the log when playing and using the tools with negative durability? We should have a check in place that should produce some log entries if that is the case.

**Comment by Gamerbolts** [comment]
It does seem to be once in awhile, but I will check and get back to you. I am thinking a possible conflict with FTB Ultamine. I did however change the config in Forgero to not make tools unbreakable so that may fix it if it just breaks the tool instead, but I'll test next time I get my modpack open and see

**Comment by SigmundGranaas** [comment]
Note: I encountered this in scenarios where the tool has higher durability, and then looses an upgrade which lowered the tools durability, which caused the tool damage to be higher than the durability of the tool.
