### ISSUE TITLE
Bindings disappear after sword is crafted

### ISSUE THREAD

**Issue by peter-ni** [SigmundGranaas/forgero#830]
**Versions**
Minecraft: 1.20.1
Fabric: 0.15.3
Forgero: 0.11.11+1.20.1 (Jan 6 release)

After crafting a sword in the diagonal pattern in the crafting table (handle, binding, blade), the binding disappears from the crafted sword and the item tooltip does not show it. The sword still retains the properties that the binding changes which I confirmed by checking the weight after putting on gold spiked binding + ender gem. Sword guards work fine and don't have this issue. In the inventory screen, it sometimes "flickers" and glitches, switching to some glitched png. I was not able to capture this in a screen recording, but it happens sometimes and I think it is related to the binding issue.  

https://github.com/SigmundGranaas/forgero/assets/30128037/72357d58-8ce5-4104-ae54-f17647271bed

Sorry, I know the video isn't really helpful because I couldn't capture the png glitching but that's what the tooltip looks like. Sometimes, the binding works I think though when crafting a sword. I recall reading a similar binding issue for a previous version, but I can't find the GitHub link now. I'm not too familiar with logging stuff in Minecraft but I can try to provide you with more context if you point me in the right direction. Thanks and great work over the past year !!

**Comment by JorisDeBeer** [comment]
Bindings should not be on swords. They have guards instead, so it doesnt have a texture thats why it doesnt show. Probably a recipe rework overlook caused this. Will be fixed

**Comment by JorisDeBeer** [comment]
Fixed #929
