### ISSUE TITLE
Parsing error loading recipe spam

### ISSUE THREAD

**Issue by LeoDemitori** [SigmundGranaas/forgero#831]
Spam errors in server-client logs: **Parsing error loading recipe**

Full logs:
[latest.log](https://github.com/SigmundGranaas/forgero/files/14223244/latest.log)

How to fix this?

Version 0.11.11
Fabric

**Comment by JorisDeBeer** [comment]
Hi! 

Thanks for opening a bug report.

First of all I see you have made your own compat packs for some mods? As there are multiple references which I dont recognise. 

Do think its a problem on our side tho, the recipe generator got some changes and this is probably the aftermath for addons. 

Could you check for me if the ID's do fit for the addon packs you made? or did you use something to automatically generate those parts?

**Comment by LeoDemitori** [comment]
what compat packs do you mean?

I use datapacks only for generating structures and biomes (terralith)
I also use the following similar mods:

AlmostUnified
ToolLeveling
AlloyForgery

**Comment by JorisDeBeer** [comment]
hmm. Not Sure then. There are alot of errors also not from forgero then. Probably coming from almost unified? 

The betternether compat is probably broken on our end, only means that the current tools from them dont work. We need to fix this, you cant.
