### ISSUE TITLE
Mythic Metals - Banglum material has 11 base damage

### ISSUE THREAD

**Issue by CaesarSP** [SigmundGranaas/forgero#839]
I doubt such high damage for a low-tier material is intended, so I figured it might be relevant to put it here. 
If it's intended... Well, that feels a little unbalanced. Thanks in advance.

![Captura de pantalla (269)](https://github.com/SigmundGranaas/forgero/assets/138718742/0972483a-d2a2-4ee0-bf21-bac9b98ae2f8)

**Comment by SigmundGranaas** [comment]
That is indeed very high, let me double check the config. Thanks for the heads up :+1:
