### ISSUE TITLE
Create extendo grip don't work with Forgero instruments

### ISSUE THREAD

**Issue by NightSculptor** [SigmundGranaas/forgero#880]
The tools perform their function, but extending the range of interaction from extendo grip does not work.

**Comment by SigmundGranaas** [comment]
I assume you are referring to the[Extendo grip from create](https://create.fandom.com/wiki/Extendo_Grip). Forgero implements it's own functionality for setting the range of tools which is probably incompatible with how Create sets it. I could look into not explicitly overriding the range value, but rather adding/subtracting what we are expecting the baseline value to be, so it can be possible for other mods to interact with this value.
