### ISSUE TITLE
typo in Forgero Reference (ingame guide book)

### ISSUE THREAD

**Issue by PaterFrog** [SigmundGranaas/forgero#925]
The descriptions for Quick and Lucky are the same:
![image](https://github.com/SigmundGranaas/forgero/assets/46433636/75bb54bd-4701-484a-b5cd-16919ce5573b)

**Comment by PaterFrog** [comment]
Reading a little further, I notice that many conditions have the same description. If this is a matter of tiers, please update accordingly.

**Comment by JorisDeBeer** [comment]
Thank you! But sadly we wont be fixing this as we a migrating to modonomicon and leaving patchouli behind as it does not get updated anymore. So expect to see a whole different and more complete book soon!
