### ISSUE TITLE
InGame Guide Book

### ISSUE THREAD

**Issue by VPintos2501** [SigmundGranaas/forgero#926]
Hi, the issue that I detected is that when trying to craft the guide book in the way it says in the description (a tool part and a book) it does not give me the guide, and since I have certain doubts regarding crafting and functionalities, and it would be useful to have it. I don't know if the error is due to something in Patchouli or the mod itself.

**Comment by JorisDeBeer** [comment]
Which version are you playing? 

Patchouli is disabled in some (I think) because of broken stuff. Just keep in mind that the patchouli book is old, outdated and unfinished.

**Comment by VPintos2501** [comment]
I'm playing in 1.20.4

**Comment by JorisDeBeer** [comment]
In the next version there will be a fully up to date modonomicon book use that please
