### ISSUE TITLE
Our own arrows cant be given potion effects

### ISSUE THREAD

**Issue by JorisDeBeer** [SigmundGranaas/forgero#932]
I am not sure how we would implement this.

**Comment by SigmundGranaas** [comment]
Hold my json

**Comment by SigmundGranaas** [comment]
![image](https://github.com/user-attachments/assets/79ed641f-476e-4f56-8aff-586174e775f4)

Fermented spider eye json:
```
    "features": [
      {
        "type": "minecraft:on_hit",
        "on_hit": {
          "type": "minecraft:status_effect",
          "target": "minecraft:targeted_entity",
          "effect": "minecraft:poison",
          "level": 1
        },
        "title": "Poison",
        "description": "Applies poison on hit"
      }
    ]
```



Mastercrafted arrow head json:
```
"slots": [
      {
        "category": [
          "OFFENSIVE"
        ],
        "description": "upgrade",
        "type": "UPGRADE_MATERIAL",
        "tier": 1
      }
    ]
```

![image](https://github.com/user-attachments/assets/9a765651-1006-4d0a-bc54-6d54277f88f1)


https://github.com/user-attachments/assets/d6f476a2-f20a-4f6e-87ed-6b19f03f6257

**Comment by JorisDeBeer** [comment]
how does this scale with the arrows? Do they get alot heavier because of the added weight?

**Comment by SigmundGranaas** [comment]
We can adjust the upgrade weight, it's currently at 10.

**Comment by JorisDeBeer** [comment]
Shall I add this to the handler branch I was working on recently? This adds alot of the status effects from minecraft itself. So I will just add the upgrade slots on arrows on that too

**Comment by SigmundGranaas** [comment]
That would probably work well :+1:

**Comment by JorisDeBeer** [comment]
Implemented
