### ISSUE TITLE
Valkyrien Skies 2 compatibility

### ISSUE THREAD

**Issue by mmfam** [SigmundGranaas/forgero#936]
Forgero crashes at world generation menu when launching with Valkyrien Skies.

**Comment by JorisDeBeer** [comment]
without log no fix

**Comment by mmfam** [comment]
Whoops, sorry.

[latest.log](https://github.com/user-attachments/files/16202752/latest.log)

**Comment by JorisDeBeer** [comment]
ServerInteractionManagerReachMixin is the problem here, we are already looking to change this as it also breaks our mod with sinytra so hopefully in the next update

**Comment by mmfam** [comment]
Awesome, thank you.

**Comment by darceno** [comment]
This was closed, but the crash still happens. A compatibility would be much appreciate, I love this mod.
[crash-2024-08-26_22.26.20-client.txt](https://github.com/user-attachments/files/16755272/crash-2024-08-26_22.26.20-client.txt)

**Comment by SigmundGranaas** [comment]
The patch that fixes this issue has not yet been published to curseforge or modrinth. I expect to release the latest version in a couple of days!

**Comment by darceno** [comment]
Oh, great. Looking forward to it!

**Comment by Steveplays28** [comment]
Fixed in [`v0.12.5`](https://github.com/SigmundGranaas/forgero/releases/latest).
